/**
 * The operation registry — every capability Open Run exposes, as data.
 *
 * This list is the single source of truth for the whole API surface. The
 * server functions in `fns/index.ts`, the versioned REST routes under
 * `routes/api/v1/**`, the typed fetch client, the OpenAPI document and the
 * Swift `OpenRunKit` package are all generated from it — so a capability is
 * described once and cannot drift between transports.
 *
 * Adding an operation: add an entry here, run `pnpm contract:generate`, and
 * export the named function from `server/core.ts`. The dispatch test fails if
 * `core` names an export that does not exist.
 *
 * Generated from the hand-written server functions during the contract
 * migration; hand-maintained from here on.
 *
 * Pure data. No imports beyond types, no `node:` anything, browser-safe.
 */
import type { Operation } from './types.ts'

export const OPERATIONS = [
  // --- cloud ---------------------------------------------------------------
  {
    id: 'cloud.status',
    fn: 'cloudStatus',
    method: 'GET',
    path: '/api/v1/cloud/status',
    core: 'getCloudStatus',
    args: 'none',
    input: null,
    capability: 'cloud.status',
    clients: ['web', 'desktop'],
  },
  {
    id: 'cloud.startLogin',
    fn: 'startCloudLogin',
    method: 'POST',
    path: '/api/v1/cloud/start-login',
    core: 'startCloudLogin',
    args: ['origin', 'next'],
    input: { origin: 'string', next: 'string?' },
    capability: 'cloud.startLogin',
    clients: ['web', 'desktop'],
    inputType: '{ origin: string; next?: string }',
  },
  {
    id: 'cloud.completeLogin',
    fn: 'completeCloudLogin',
    method: 'POST',
    path: '/api/v1/cloud/complete-login',
    core: 'completeCloudLoginAndFinish',
    args: 'payload',
    input: { code: 'string', state: 'string' },
    capability: 'cloud.completeLogin',
    clients: ['web', 'desktop'],
    inputType: '{ code: string; state: string }',
  },
  {
    id: 'cloud.providers',
    fn: 'cloudProviders',
    method: 'GET',
    path: '/api/v1/cloud/providers',
    core: 'listCloudProviders',
    args: 'none',
    input: null,
    capability: 'cloud.providers',
    clients: ['web', 'desktop'],
    summary: 'Which providers this control plane can connect. Public — no session needed.',
  },
  {
    id: 'cloud.skipOnboarding',
    fn: 'skipCloudOnboarding',
    method: 'POST',
    path: '/api/v1/cloud/skip-onboarding',
    core: 'skipCloudOnboarding',
    args: 'none',
    input: null,
    capability: 'cloud.skipOnboarding',
    clients: ['web', 'desktop'],
  },
  {
    id: 'cloud.signOut',
    fn: 'signOutCloud',
    method: 'POST',
    path: '/api/v1/cloud/sign-out',
    core: 'signOutAndDisconnect',
    args: 'none',
    input: null,
    returnsOk: true,
    capability: 'cloud.signOut',
    clients: ['web', 'desktop'],
  },
  {
    id: 'cloud.startHostedConnect',
    fn: 'startHostedConnect',
    method: 'POST',
    path: '/api/v1/cloud/start-hosted-connect',
    core: 'startHostedConnect',
    args: 'payload',
    input: { provider: 'string', origin: 'string' },
    capability: 'cloud.startHostedConnect',
    clients: ['web', 'desktop'],
    inputType: '{ provider: string; origin: string }',
  },
  {
    id: 'cloud.completeHostedConnect',
    fn: 'completeHostedConnect',
    method: 'POST',
    path: '/api/v1/cloud/complete-hosted-connect',
    core: 'completeHostedConnect',
    args: 'payload',
    input: {
      provider: 'string',
      cloudConnectionId: 'string',
      state: 'string?',
      siteUrl: 'string?',
      accountName: 'string?',
    },
    capability: 'cloud.completeHostedConnect',
    clients: ['web', 'desktop'],
    inputType:
      '{ provider: string; cloudConnectionId: string; state?: string; siteUrl?: string; accountName?: string }',
  },
  {
    id: 'cloud.listHostedConnections',
    fn: 'listHostedConnections',
    method: 'GET',
    path: '/api/v1/cloud/list-hosted-connections',
    core: 'listHostedConnections',
    args: 'none',
    input: null,
    capability: 'cloud.listHostedConnections',
    clients: ['web', 'desktop'],
  },

  // --- dashboard -----------------------------------------------------------
  {
    id: 'dashboard.dashboard',
    fn: 'dashboard',
    method: 'GET',
    path: '/api/v1/dashboard/dashboard',
    core: 'getDashboard',
    args: 'none',
    input: null,
    capability: 'dashboard',
    clients: ['web', 'desktop', 'mobile'],
  },

  // --- devices -------------------------------------------------------------
  {
    id: 'devices.mobileStatus',
    fn: 'mobileStatus',
    method: 'GET',
    path: '/api/v1/devices/mobile-status',
    core: 'mobileStatus',
    args: 'none',
    input: null,
    capability: 'devices.mobileStatus',
    clients: ['web', 'desktop'],
  },
  {
    id: 'devices.createPairingCode',
    fn: 'createPairingCode',
    method: 'POST',
    path: '/api/v1/devices/create-pairing-code',
    core: 'createPairingCode',
    args: 'none',
    input: null,
    capability: 'devices.createPairingCode',
    clients: ['web', 'desktop'],
  },
  {
    id: 'devices.cancelPairing',
    fn: 'cancelPairing',
    method: 'POST',
    path: '/api/v1/devices/cancel-pairing',
    core: 'cancelPairing',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'devices.cancelPairing',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'devices.revoke',
    fn: 'revokeDevice',
    method: 'POST',
    path: '/api/v1/devices/revoke',
    core: 'revokeDevice',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'devices.revoke',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'devices.remove',
    fn: 'removeDevice',
    method: 'POST',
    path: '/api/v1/devices/remove',
    core: 'deleteDevice',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'devices.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },

  // --- files ---------------------------------------------------------------
  {
    id: 'files.listWorkspace',
    fn: 'listWorkspaceFiles',
    method: 'GET',
    path: '/api/v1/files/list-workspace',
    core: 'listWorkspaceFiles',
    args: 'payload',
    input: { runId: 'string', dir: 'string?' },
    capability: 'runs.files',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string; dir?: string }',
  },
  {
    id: 'files.readWorkspace',
    fn: 'readWorkspaceFile',
    method: 'GET',
    path: '/api/v1/files/read-workspace',
    core: 'readWorkspaceFile',
    args: 'payload',
    input: { runId: 'string', path: 'string' },
    capability: 'runs.files',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string; path: string }',
  },
  {
    id: 'files.writeWorkspace',
    fn: 'writeWorkspaceFile',
    method: 'POST',
    path: '/api/v1/files/write-workspace',
    core: 'writeWorkspaceFile',
    args: 'payload',
    input: { runId: 'string', path: 'string', content: 'string' },
    capability: 'files.writeWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; path: string; content: string }',
  },
  {
    id: 'files.restoreWorkspace',
    fn: 'restoreWorkspaceFile',
    method: 'POST',
    path: '/api/v1/files/restore-workspace',
    core: 'restoreWorkspaceFile',
    args: 'payload',
    input: { runId: 'string', path: 'string', content: 'string' },
    capability: 'files.restoreWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; path: string; content: string }',
  },
  {
    id: 'files.saveAttachment',
    fn: 'saveAttachment',
    method: 'POST',
    path: '/api/v1/files/save-attachment',
    core: 'saveWorkspaceAttachment',
    args: 'payload',
    input: {
      workspaceId: 'string',
      runId: 'string?',
      name: 'string',
      mimeType: 'string',
      data: 'string',
    },
    capability: 'files.saveAttachment',
    clients: ['web', 'desktop'],
    inputType:
      '{ workspaceId: string; runId?: string; name: string; mimeType: string; data: string }',
    summary: 'Upload a composer image; `data` is raw base64 without the data-URL prefix.',
  },

  // --- code ----------------------------------------------------------------
  {
    id: 'code.highlight',
    fn: 'highlightCodeBlock',
    method: 'POST',
    path: '/api/v1/code/highlight',
    core: 'highlightCodeBlock',
    args: 'payload',
    input: { code: 'string', language: 'string?', path: 'string?' },
    capability: 'code.highlight',
    clients: ['desktop'],
    inputType: '{ code: string; language?: string; path?: string }',
    summary: "Tokenize a snippet with the app's own highlighter; answers class names, not colours.",
  },

  // --- git -----------------------------------------------------------------
  {
    id: 'git.getFileDiff',
    fn: 'getFileDiff',
    method: 'GET',
    path: '/api/v1/git/get-file-diff',
    core: 'getFileDiff',
    args: 'payload',
    input: { runId: 'string', path: 'string', whole: 'boolean?' },
    capability: 'runs.diff',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string; path: string; whole?: boolean }',
  },
  {
    id: 'git.commitChanges',
    fn: 'commitChanges',
    method: 'POST',
    path: '/api/v1/git/commit-changes',
    core: 'commitChanges',
    args: 'payload',
    input: { runId: 'string', message: 'string', paths: 'string[]?' },
    capability: 'git.commitChanges',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; message: string; paths?: string[] }',
  },
  {
    id: 'git.pushChanges',
    fn: 'pushChanges',
    method: 'POST',
    path: '/api/v1/git/push-changes',
    core: 'pushChanges',
    args: 'payload',
    input: { runId: 'string' },
    capability: 'git.pushChanges',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'git.discardChanges',
    fn: 'discardChanges',
    method: 'POST',
    path: '/api/v1/git/discard-changes',
    core: 'discardChanges',
    args: 'payload',
    input: { runId: 'string', paths: 'string[]?', resetCommits: 'boolean?' },
    capability: 'git.discardChanges',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; paths?: string[]; resetCommits?: boolean }',
  },
  {
    id: 'git.discardHunk',
    fn: 'discardHunk',
    method: 'POST',
    path: '/api/v1/git/discard-hunk',
    core: 'discardHunk',
    args: 'payload',
    input: { runId: 'string', path: 'string', hunkIndex: 'number' },
    capability: 'git.discardHunk',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; path: string; hunkIndex: number }',
  },
  {
    id: 'git.createBranch',
    fn: 'createBranch',
    method: 'POST',
    path: '/api/v1/git/create-branch',
    core: 'createBranch',
    args: 'payload',
    input: { runId: 'string', name: 'string' },
    capability: 'git.createBranch',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; name: string }',
  },
  {
    id: 'git.openPullRequest',
    fn: 'openPullRequest',
    method: 'POST',
    path: '/api/v1/git/open-pull-request',
    core: 'openPullRequest',
    args: 'payload',
    input: { runId: 'string', title: 'string', body: 'string', base: 'string?' },
    capability: 'git.openPullRequest',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; title: string; body: string; base?: string }',
  },
  {
    id: 'git.shipRun',
    fn: 'shipRun',
    method: 'POST',
    path: '/api/v1/git/ship-run',
    core: 'shipRun',
    args: 'payload',
    input: { runId: 'string', base: 'string?', skipPlan: 'boolean?' },
    capability: 'git.shipRun',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; base?: string; skipPlan?: boolean }',
  },
  {
    id: 'git.listProjectBranches',
    fn: 'listProjectBranches',
    method: 'GET',
    path: '/api/v1/git/list-project-branches',
    core: 'listProjectBranches',
    args: ['projectId'],
    input: { projectId: 'string' },
    capability: 'git.listProjectBranches',
    clients: ['web', 'desktop'],
    inputType: '{ projectId: string }',
  },

  // --- integrations --------------------------------------------------------
  {
    id: 'integrations.listProviders',
    fn: 'listIntegrationProviders',
    method: 'GET',
    path: '/api/v1/integrations/list-providers',
    core: 'listProviderCatalog',
    args: 'none',
    input: null,
    capability: 'integrations.listProviders',
    clients: ['web', 'desktop'],
  },
  {
    id: 'integrations.list',
    fn: 'listIntegrations',
    method: 'GET',
    path: '/api/v1/integrations/list',
    core: 'listIntegrations',
    args: 'none',
    input: null,
    capability: 'integrations.list',
    clients: ['web', 'desktop'],
  },
  {
    id: 'integrations.get',
    fn: 'getIntegration',
    method: 'GET',
    path: '/api/v1/integrations/get',
    core: 'getIntegrationPublic',
    args: ['id'],
    input: { id: 'string' },
    nullable: true,
    capability: 'integrations.get',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'integrations.create',
    fn: 'createIntegration',
    method: 'POST',
    path: '/api/v1/integrations/create',
    core: 'createIntegration',
    args: 'payload',
    input: { provider: 'string' },
    capability: 'integrations.create',
    clients: ['web', 'desktop'],
    inputType: 'CreateIntegrationInput',
  },
  {
    id: 'integrations.update',
    fn: 'updateIntegration',
    method: 'POST',
    path: '/api/v1/integrations/update',
    core: 'updateIntegration',
    args: 'payload',
    input: { id: 'string' },
    capability: 'integrations.update',
    clients: ['web', 'desktop'],
    inputType: 'UpdateIntegrationInput',
  },
  {
    id: 'integrations.listWebhookDeliveries',
    fn: 'listWebhookDeliveries',
    method: 'GET',
    path: '/api/v1/integrations/list-webhook-deliveries',
    core: 'listWebhookDeliveries',
    args: 'payload',
    input: { integrationId: 'string?', limit: 'number?' },
    inputOptional: true,
    capability: 'integrations.listWebhookDeliveries',
    clients: ['web', 'desktop'],
    inputType: '{ integrationId?: string; limit?: number }',
  },
  {
    id: 'integrations.getAutomationSetupContext',
    fn: 'getAutomationSetupContext',
    method: 'GET',
    path: '/api/v1/integrations/get-automation-setup-context',
    core: 'getAutomationSetupContext',
    args: 'none',
    input: null,
    capability: 'integrations.getAutomationSetupContext',
    clients: ['web', 'desktop'],
  },
  {
    id: 'integrations.createAutomation',
    fn: 'createIntegrationAutomation',
    method: 'POST',
    path: '/api/v1/integrations/create-automation',
    core: 'createIntegrationAutomation',
    args: 'payload',
    input: {
      integrationId: 'string',
      workspaceId: 'string',
      runtimeId: 'string',
      trigger: 'object?',
      events: 'string[]?',
      name: 'string?',
      prompt: 'string?',
      enabled: 'boolean?',
    },
    capability: 'integrations.createAutomation',
    clients: ['web', 'desktop'],
    inputType: 'CreateIntegrationAutomationInput',
    summary: 'Bind a connected integration to a workspace + runtime so deliveries run.',
  },
  {
    id: 'integrations.disconnectHosted',
    fn: 'disconnectHostedIntegration',
    method: 'POST',
    path: '/api/v1/integrations/disconnect-hosted',
    core: 'disconnectHostedIntegration',
    args: ['integrationId'],
    input: { integrationId: 'string' },
    capability: 'integrations.disconnectHosted',
    clients: ['web', 'desktop'],
    inputType: '{ integrationId: string }',
  },
  {
    id: 'integrations.ingestTestEvent',
    fn: 'ingestTestEvent',
    method: 'POST',
    path: '/api/v1/integrations/ingest-test-event',
    core: 'ingestTestEvent',
    args: ['integrationId'],
    input: { integrationId: 'string' },
    capability: 'integrations.ingestTestEvent',
    clients: ['web', 'desktop'],
    inputType: '{ integrationId: string }',
  },

  // --- mcp -----------------------------------------------------------------
  {
    id: 'mcp.getConfig',
    fn: 'getMcpConfig',
    method: 'GET',
    path: '/api/v1/mcp/get-config',
    core: 'getMcpConfig',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string?' },
    capability: 'mcp.getConfig',
    clients: ['web', 'desktop'],
    inputType: '{ runtimeId: string; workspaceId?: string }',
  },
  {
    id: 'mcp.saveServer',
    fn: 'saveMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/save-server',
    core: 'saveMcpServerConfig',
    args: 'payload',
    input: {
      runtimeId: 'string',
      workspaceId: 'string?',
      targetId: 'string',
      server: 'object',
      previousName: 'string?',
    },
    capability: 'mcp.saveServer',
    clients: ['web', 'desktop'],
    inputType:
      '{ runtimeId: string; workspaceId?: string; targetId: string; server: McpServerConfig; previousName?: string }',
  },
  {
    id: 'mcp.removeServer',
    fn: 'removeMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/remove-server',
    core: 'removeMcpServerConfig',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string?', targetId: 'string', name: 'string' },
    capability: 'mcp.removeServer',
    clients: ['web', 'desktop'],
    inputType: '{ runtimeId: string; workspaceId?: string; targetId: string; name: string }',
  },
  {
    id: 'mcp.getShared',
    fn: 'getSharedMcp',
    method: 'GET',
    path: '/api/v1/mcp/get-shared',
    core: 'getSharedMcpConfig',
    args: 'none',
    input: null,
    capability: 'mcp.getShared',
    clients: ['web', 'desktop'],
  },
  {
    id: 'mcp.saveSharedServer',
    fn: 'saveSharedMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/save-shared-server',
    core: 'saveSharedMcpServerConfig',
    args: 'payload',
    input: { server: 'object', previousName: 'string?', force: 'boolean?' },
    capability: 'mcp.saveSharedServer',
    clients: ['web', 'desktop'],
    inputType: '{ server: McpServerConfig; previousName?: string; force?: boolean }',
  },
  {
    id: 'mcp.removeSharedServer',
    fn: 'removeSharedMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/remove-shared-server',
    core: 'removeSharedMcpServerConfig',
    args: 'payload',
    input: { name: 'string', scope: 'string?' },
    capability: 'mcp.removeSharedServer',
    clients: ['web', 'desktop'],
    inputType: "{ name: string; scope?: 'registry' | 'everywhere' }",
  },
  {
    id: 'mcp.discoverServers',
    fn: 'discoverMcpServers',
    method: 'GET',
    path: '/api/v1/mcp/discover-servers',
    core: 'discoverMcpServersConfig',
    args: 'none',
    input: null,
    capability: 'mcp.discoverServers',
    clients: ['web', 'desktop'],
  },
  {
    id: 'mcp.importServers',
    fn: 'importMcpServers',
    method: 'POST',
    path: '/api/v1/mcp/import-servers',
    core: 'importMcpServersConfig',
    args: 'payload',
    input: { choices: 'array' },
    capability: 'mcp.importServers',
    clients: ['web', 'desktop'],
    inputType: '{ choices: { name: string; fromTargetId: string }[] }',
  },
  {
    id: 'mcp.getOAuthStatus',
    fn: 'getMcpOAuthStatus',
    method: 'GET',
    path: '/api/v1/mcp/get-oauth-status',
    core: 'getMcpOAuthStatus',
    args: 'none',
    input: null,
    capability: 'mcp.getOAuthStatus',
    clients: ['web', 'desktop'],
  },
  {
    id: 'mcp.startOAuth',
    fn: 'startMcpOAuth',
    method: 'POST',
    path: '/api/v1/mcp/start-oauth',
    core: 'startMcpOAuth',
    args: 'payload',
    input: { name: 'string', redirectUri: 'string' },
    capability: 'mcp.startOAuth',
    clients: ['web', 'desktop'],
    inputType: '{ name: string; redirectUri: string }',
  },
  {
    id: 'mcp.disconnectServer',
    fn: 'disconnectMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/disconnect-server',
    core: 'disconnectMcpServer',
    args: 'payload',
    input: { name: 'string' },
    capability: 'mcp.disconnectServer',
    clients: ['web', 'desktop'],
    inputType: '{ name: string }',
  },
  {
    id: 'mcp.syncShared',
    fn: 'syncSharedMcp',
    method: 'POST',
    path: '/api/v1/mcp/sync-shared',
    core: 'syncSharedMcpConfig',
    args: 'payload',
    input: { force: 'boolean?' },
    inputOptional: true,
    capability: 'mcp.syncShared',
    clients: ['web', 'desktop'],
    inputType: '{ force?: boolean }',
  },

  // --- notifications -------------------------------------------------------
  {
    id: 'notifications.listNotifiers',
    fn: 'listNotifiers',
    method: 'GET',
    path: '/api/v1/notifications/list-notifiers',
    core: 'listNotifiers',
    args: 'none',
    input: null,
    capability: 'notifications.listNotifiers',
    clients: ['web', 'desktop'],
  },
  {
    id: 'notifications.saveNotifier',
    fn: 'saveNotifier',
    method: 'POST',
    path: '/api/v1/notifications/save-notifier',
    core: 'upsertNotifier',
    args: 'payload',
    input: { kind: 'string', name: 'string', target: 'string?', enabled: 'boolean' },
    capability: 'notifications.saveNotifier',
    clients: ['web', 'desktop'],
    inputType: 'NotifierInput',
  },
  {
    id: 'notifications.removeNotifier',
    fn: 'removeNotifier',
    method: 'POST',
    path: '/api/v1/notifications/remove-notifier',
    core: 'deleteNotifier',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'notifications.removeNotifier',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'notifications.testNotifier',
    fn: 'testNotifier',
    method: 'POST',
    path: '/api/v1/notifications/test-notifier',
    core: 'testNotifier',
    args: ['id'],
    input: { id: 'string' },
    capability: 'notifications.testNotifier',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'notifications.listDeliveries',
    fn: 'listNotificationDeliveries',
    method: 'GET',
    path: '/api/v1/notifications/list-deliveries',
    core: 'listNotificationDeliveries',
    args: 'payload',
    input: { notifierId: 'string?', limit: 'number?' },
    inputOptional: true,
    capability: 'notifications.listDeliveries',
    clients: ['web', 'desktop'],
    inputType: '{ notifierId?: string; limit?: number }',
  },

  // --- planner -------------------------------------------------------------
  {
    id: 'planner.planObjective',
    fn: 'planObjective',
    method: 'POST',
    path: '/api/v1/planner/plan-objective',
    core: 'planObjective',
    args: 'payload',
    input: { objective: 'string', runtimeId: 'string', workspaceId: 'string' },
    capability: 'planner.planObjective',
    clients: ['web', 'desktop'],
    inputType: '{ objective: string; runtimeId: string; workspaceId: string }',
  },
  {
    id: 'planner.installPlanProposal',
    fn: 'installPlanProposal',
    method: 'POST',
    path: '/api/v1/planner/install-plan-proposal',
    core: 'installPlanProposal',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string', proposal: 'object', enabled: 'boolean?' },
    capability: 'planner.installPlanProposal',
    clients: ['web', 'desktop'],
    inputType:
      '{ runtimeId: string; workspaceId: string; proposal: PlanProposal; enabled?: boolean }',
  },

  // --- plugins -------------------------------------------------------------
  {
    id: 'plugins.list',
    fn: 'listPlugins',
    method: 'GET',
    path: '/api/v1/plugins/list',
    core: 'listPluginsFor',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string?' },
    capability: 'plugins.list',
    clients: ['web', 'desktop'],
    inputType: '{ runtimeId: string; workspaceId?: string }',
  },
  {
    id: 'plugins.listInstalled',
    fn: 'listInstalledPlugins',
    method: 'GET',
    path: '/api/v1/plugins/list-installed',
    core: 'listInstalledPlugins',
    args: 'payload',
    input: { workspaceId: 'string?' },
    inputOptional: true,
    capability: 'plugins.listInstalled',
    clients: ['web', 'desktop'],
    inputType: '{ workspaceId?: string }',
  },

  // --- projects ------------------------------------------------------------
  {
    id: 'projects.list',
    fn: 'listProjects',
    method: 'GET',
    path: '/api/v1/projects/list',
    core: 'listProjects',
    args: 'none',
    input: null,
    capability: 'projects.list',
    clients: ['web', 'desktop'],
  },
  {
    id: 'projects.listLocalDirectories',
    fn: 'listLocalDirectories',
    method: 'GET',
    path: '/api/v1/projects/list-local-directories',
    core: 'listLocalDirectories',
    args: ['dir', 'showHidden'],
    input: { dir: 'string?', showHidden: 'boolean?' },
    inputOptional: true,
    capability: 'projects.listLocalDirectories',
    clients: ['web', 'desktop'],
    inputType: '{ dir?: string; showHidden?: boolean }',
  },
  {
    id: 'projects.listLocalPlaces',
    fn: 'listLocalPlaces',
    method: 'GET',
    path: '/api/v1/projects/list-local-places',
    core: 'listLocalPlaces',
    args: 'none',
    input: null,
    capability: 'projects.listLocalPlaces',
    clients: ['web', 'desktop'],
  },
  {
    id: 'projects.createLocalFolder',
    fn: 'createLocalFolder',
    method: 'POST',
    path: '/api/v1/projects/create-local-folder',
    core: 'createLocalFolder',
    args: 'payload',
    input: { parent: 'string?', name: 'string' },
    capability: 'projects.createLocalFolder',
    clients: ['web', 'desktop'],
    inputType: '{ parent?: string; name: string }',
  },
  {
    id: 'projects.add',
    fn: 'addProject',
    method: 'POST',
    path: '/api/v1/projects/add',
    core: 'addProject',
    args: 'payload',
    input: {
      mode: 'string',
      url: 'string?',
      path: 'string?',
      name: 'string?',
      setupCommand: 'string?',
    },
    capability: 'projects.add',
    clients: ['web', 'desktop'],
    inputType:
      "{ mode: 'clone' | 'register'; url?: string; path?: string; name?: string; setupCommand?: string }",
  },
  {
    id: 'projects.update',
    fn: 'updateProject',
    method: 'POST',
    path: '/api/v1/projects/update',
    core: 'updateProject',
    args: 'payload',
    input: {
      id: 'string',
      name: 'string?',
      setupCommand: 'string?',
      defaultBranch: 'string?',
      checks: 'array?',
    },
    capability: 'projects.update',
    clients: ['web', 'desktop'],
    inputType:
      '{ id: string; name?: string; setupCommand?: string; defaultBranch?: string; checks?: CheckDef[] }',
  },
  {
    id: 'projects.suggestChecks',
    fn: 'suggestProjectChecks',
    method: 'POST',
    path: '/api/v1/projects/suggest-checks',
    core: 'suggestProjectChecks',
    args: ['id'],
    input: { id: 'string' },
    capability: 'projects.suggestChecks',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
    summary: 'Checks Open Run would propose for this repo, from its package.json scripts.',
  },
  {
    id: 'projects.remove',
    fn: 'removeProject',
    method: 'POST',
    path: '/api/v1/projects/remove',
    core: 'deleteProject',
    args: ['id', 'deleteFiles'],
    input: { id: 'string', deleteFiles: 'boolean' },
    returnsOk: true,
    capability: 'projects.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string; deleteFiles: boolean }',
  },

  // --- runs ----------------------------------------------------------------
  {
    id: 'runs.listNativeSessions',
    fn: 'listNativeSessions',
    method: 'GET',
    path: '/api/v1/runs/list-native-sessions',
    core: 'listNativeSessions',
    args: 'payload',
    input: {
      workspaceId: 'string?',
      allWorkspaces: 'boolean?',
      kind: 'string?',
      offset: 'number?',
      limit: 'number?',
    },
    capability: 'runs.listNativeSessions',
    clients: ['web', 'desktop'],
    inputType:
      "{ workspaceId?: string; allWorkspaces?: boolean; kind?: 'claude' | 'codex' | 'grok' | 'antigravity'; offset?: number; limit?: number }",
  },
  {
    id: 'runs.list',
    fn: 'listRuns',
    method: 'GET',
    path: '/api/v1/runs/list',
    core: 'listRuns',
    args: 'payload',
    input: { taskId: 'string?', limit: 'number?', offset: 'number?', includeArchived: 'boolean?' },
    inputOptional: true,
    capability: 'runs.list',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ taskId?: string; limit?: number; offset?: number; includeArchived?: boolean }',
  },
  {
    id: 'runs.listConversationNavigation',
    fn: 'listConversationNavigationRuns',
    method: 'GET',
    path: '/api/v1/runs/list-conversation-navigation',
    core: 'listConversationNavigationRuns',
    args: 'none',
    input: null,
    capability: 'runs.listConversationNavigation',
    clients: ['web', 'desktop'],
  },
  {
    id: 'runs.count',
    fn: 'countRuns',
    method: 'GET',
    path: '/api/v1/runs/count',
    core: 'countRuns',
    args: 'payload',
    input: { taskId: 'string?', includeArchived: 'boolean?' },
    inputOptional: true,
    capability: 'runs.count',
    clients: ['web', 'desktop'],
    inputType: '{ taskId?: string; includeArchived?: boolean }',
  },
  {
    id: 'runs.listChecks',
    fn: 'listRunChecks',
    method: 'GET',
    path: '/api/v1/runs/list-checks',
    core: 'listRunChecks',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.listChecks',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.reRunChecks',
    fn: 'rerunRunChecks',
    method: 'POST',
    path: '/api/v1/runs/re-run-checks',
    core: 'rerunRunChecks',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.reRunChecks',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.get',
    fn: 'getRun',
    method: 'GET',
    path: '/api/v1/runs/get',
    core: 'getRun',
    args: ['id'],
    input: { id: 'string' },
    nullable: true,
    capability: 'runs.read',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ id: string }',
  },
  {
    id: 'runs.cancel',
    fn: 'cancelRun',
    method: 'POST',
    path: '/api/v1/runs/cancel',
    core: 'cancelRun',
    args: ['id'],
    input: { id: 'string' },
    nullable: true,
    capability: 'runs.cancel',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ id: string }',
  },
  {
    id: 'runs.markRead',
    fn: 'markRunRead',
    method: 'POST',
    path: '/api/v1/runs/mark-read',
    core: 'markRunRead',
    args: ['id'],
    input: { id: 'string' },
    capability: 'runs.markRead',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'runs.remove',
    fn: 'removeRun',
    method: 'POST',
    path: '/api/v1/runs/remove',
    core: 'deleteRun',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'runs.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'runs.delete',
    fn: 'deleteRuns',
    method: 'POST',
    path: '/api/v1/runs/delete',
    core: 'deleteRuns',
    args: ['ids'],
    input: { ids: 'string[]' },
    returnsOk: true,
    capability: 'runs.delete',
    clients: ['web', 'desktop'],
    inputType: '{ ids: string[] }',
  },
  {
    id: 'runs.getLatestForWorkspace',
    fn: 'getLatestRunForWorkspace',
    method: 'GET',
    path: '/api/v1/runs/get-latest-for-workspace',
    core: 'getLatestRunForWorkspace',
    args: ['workspaceId'],
    input: { workspaceId: 'string' },
    capability: 'runs.getLatestForWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ workspaceId: string }',
  },
  {
    id: 'runs.getLatestForProject',
    fn: 'getLatestRunForProject',
    method: 'GET',
    path: '/api/v1/runs/get-latest-for-project',
    core: 'getLatestRunForProject',
    args: ['projectId'],
    input: { projectId: 'string' },
    capability: 'runs.getLatestForProject',
    clients: ['web', 'desktop'],
    inputType: '{ projectId: string }',
  },
  {
    id: 'runs.startOptions',
    fn: 'startRunOptions',
    method: 'GET',
    path: '/api/v1/runs/start-options',
    core: 'startRunOptions',
    args: 'none',
    input: null,
    capability: 'runs.startOptions',
    clients: ['web', 'desktop', 'mobile'],
  },
  {
    id: 'runs.repeat',
    fn: 'repeatRun',
    method: 'POST',
    path: '/api/v1/runs/repeat',
    core: 'repeatRun',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.create',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.startChat',
    fn: 'startChat',
    method: 'POST',
    path: '/api/v1/runs/start-chat',
    core: 'startChat',
    args: 'payload',
    input: {
      workspaceId: 'string',
      runtimeId: 'string',
      prompt: 'string',
      model: 'string?',
      effort: 'string?',
      runtimeMode: 'string?',
      resumeSessionId: 'string?',
      resumeSessionLabel: 'string?',
    },
    capability: 'runs.create',
    clients: ['web', 'desktop', 'mobile'],
    inputType:
      '{ workspaceId: string; runtimeId: string; prompt: string; model?: string; effort?: string; runtimeMode?: string; resumeSessionId?: string; resumeSessionLabel?: string }',
  },
  {
    id: 'runs.openNativeChat',
    fn: 'openNativeChat',
    method: 'POST',
    path: '/api/v1/runs/open-native-chat',
    core: 'openNativeChat',
    args: 'payload',
    input: {
      workspaceId: 'string',
      runtimeId: 'string',
      sessionId: 'string',
      sessionLabel: 'string?',
      model: 'string?',
      effort: 'string?',
      runtimeMode: 'string?',
    },
    capability: 'runs.openNativeChat',
    clients: ['web', 'desktop'],
    inputType:
      '{ workspaceId: string; runtimeId: string; sessionId: string; sessionLabel?: string; model?: string; effort?: string; runtimeMode?: string }',
  },
  {
    id: 'runs.getConversation',
    fn: 'getConversation',
    method: 'GET',
    path: '/api/v1/runs/get-conversation',
    core: 'getConversation',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.read',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.getWorkspace',
    fn: 'getRunWorkspace',
    method: 'GET',
    path: '/api/v1/runs/get-workspace',
    core: 'getRunWorkspace',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.diff',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.getPullRequest',
    fn: 'getRunPullRequest',
    method: 'GET',
    path: '/api/v1/runs/get-pull-request',
    core: 'getRunPullRequest',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.getPullRequest',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.postMessage',
    fn: 'postMessage',
    method: 'POST',
    path: '/api/v1/runs/post-message',
    core: 'postMessage',
    args: 'payload',
    input: {
      runId: 'string',
      prompt: 'string',
      runtimeId: 'string?',
      model: 'string?',
      effort: 'string?',
      runtimeMode: 'string?',
      userMessageId: 'string?',
      assistantMessageId: 'string?',
      force: 'boolean?',
    },
    capability: 'runs.message',
    clients: ['web', 'desktop', 'mobile'],
    inputType:
      '{ runId: string; prompt: string; runtimeId?: string; model?: string; effort?: string; runtimeMode?: string; userMessageId?: string; assistantMessageId?: string; force?: boolean }',
  },
  {
    id: 'runs.dequeueMessage',
    fn: 'dequeueMessage',
    method: 'POST',
    path: '/api/v1/runs/dequeue-message',
    core: 'dequeueFollowUp',
    args: 'payload',
    input: { id: 'string' },
    capability: 'runs.dequeueMessage',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
    summary: 'Drop one follow-up waiting on the current turn.',
  },
  {
    id: 'runs.clearQueuedMessages',
    fn: 'clearQueuedMessages',
    method: 'POST',
    path: '/api/v1/runs/clear-queued-messages',
    core: 'clearQueuedFollowUps',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.clearQueuedMessages',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
    summary: 'Drop every follow-up waiting on a run.',
  },
  {
    id: 'runs.flushQueuedMessages',
    fn: 'flushQueuedMessages',
    method: 'POST',
    path: '/api/v1/runs/flush-queued-messages',
    core: 'flushQueuedFollowUps',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.flushQueuedMessages',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
    summary: 'Deliver the next queued follow-up on a run that is no longer working.',
  },
  {
    id: 'runs.answerApproval',
    fn: 'answerApproval',
    method: 'POST',
    path: '/api/v1/runs/answer-approval',
    core: 'answerApproval',
    args: 'payload',
    input: {
      runId: 'string',
      requestId: 'string',
      optionId: 'string?',
      decision: 'string?',
      message: 'string?',
    },
    capability: 'approvals.answer',
    clients: ['web', 'desktop', 'mobile'],
    inputType:
      "{ runId: string; requestId: string; optionId?: string; decision?: 'allow' | 'deny'; message?: string }",
    summary:
      'Answer a pending tool-approval on a supervised run (allow/deny). The run detail UI calls this from the approval prompt; unanswered requests auto-deny on a timeout in the executor.',
  },

  // --- runtimes ------------------------------------------------------------
  {
    id: 'runtimes.list',
    fn: 'listRuntimes',
    method: 'GET',
    path: '/api/v1/runtimes/list',
    core: 'listRuntimesWithStatus',
    args: 'none',
    input: null,
    capability: 'runtimes.list',
    clients: ['web', 'desktop'],
  },
  {
    id: 'runtimes.listPresetBins',
    fn: 'listPresetBins',
    method: 'GET',
    path: '/api/v1/runtimes/list-preset-bins',
    core: 'listPresetBinStatus',
    args: 'none',
    input: null,
    capability: 'runtimes.listPresetBins',
    clients: ['web', 'desktop'],
  },
  {
    id: 'runtimes.save',
    fn: 'saveRuntime',
    method: 'POST',
    path: '/api/v1/runtimes/save',
    core: 'upsertRuntime',
    args: 'payload',
    input: { label: 'string?', bin: 'string?' },
    inputOptional: true,
    capability: 'runtimes.save',
    clients: ['web', 'desktop'],
    inputType: 'RuntimeInput',
  },
  {
    id: 'runtimes.previewCommand',
    fn: 'previewCommand',
    method: 'POST',
    path: '/api/v1/runtimes/preview-command',
    core: 'previewRuntimeCommand',
    args: 'payload',
    input: { runtimeId: 'string?', bin: 'string?' },
    inputOptional: true,
    capability: 'runtimes.previewCommand',
    clients: ['web', 'desktop'],
    inputType: 'PreviewCommandInput',
    summary:
      'Resolve the exact argv a runtime draft would spawn — no run row, no process. POST because the Runtimes editor previews an unsaved template.',
  },
  {
    id: 'runtimes.previewCommandFor',
    fn: 'previewCommandForRuntime',
    method: 'POST',
    path: '/api/v1/runtimes/preview-command-for',
    core: 'previewRuntimeCommandById',
    args: 'payload',
    input: {
      runtimeId: 'string',
      workspaceId: 'string?',
      model: 'string?',
      effort: 'string?',
      runtimeMode: 'string?',
      isFollowUp: 'boolean?',
    },
    capability: 'runtimes.previewCommandFor',
    clients: ['web', 'desktop'],
    inputType:
      '{ runtimeId: string; workspaceId?: string; model?: string; effort?: string; runtimeMode?: string; isFollowUp?: boolean }',
    summary: 'Same preview for a saved runtime, by id (tooling / non-UI callers).',
  },
  {
    id: 'runtimes.remove',
    fn: 'removeRuntime',
    method: 'POST',
    path: '/api/v1/runtimes/remove',
    core: 'deleteRuntime',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'runtimes.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },

  // --- slash ---------------------------------------------------------------
  {
    id: 'slash.listCommands',
    fn: 'listSlashCommands',
    method: 'GET',
    path: '/api/v1/slash/list-commands',
    core: 'listSlashCommandsFor',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string?', includeApp: 'boolean?' },
    capability: 'slash.listCommands',
    clients: ['web', 'desktop'],
    inputType: '{ runtimeId: string; workspaceId?: string; includeApp?: boolean }',
  },

  // --- tasks ---------------------------------------------------------------
  {
    id: 'tasks.list',
    fn: 'listTasks',
    method: 'GET',
    path: '/api/v1/tasks/list',
    core: 'listTasks',
    args: 'none',
    input: null,
    capability: 'tasks.list',
    clients: ['web', 'desktop', 'mobile'],
  },
  {
    id: 'tasks.get',
    fn: 'getTask',
    method: 'GET',
    path: '/api/v1/tasks/get',
    core: 'getTask',
    args: ['id'],
    input: { id: 'string' },
    nullable: true,
    capability: 'tasks.get',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.save',
    fn: 'saveTask',
    method: 'POST',
    path: '/api/v1/tasks/save',
    core: 'upsertTask',
    args: 'payload',
    input: {
      id: 'string?',
      name: 'string',
      description: 'string',
      runtimeId: 'string',
      prompt: 'string',
      cwd: 'string',
      workspaceId: 'string',
      cron: 'string',
      enabled: 'boolean',
      model: 'string?',
      effort: 'string?',
      webhookIntegrationId: 'string?',
      webhookEvents: 'string[]?',
      webhookFilters: 'object?',
      verifyEnabled: 'boolean?',
      maxRepairAttempts: 'number?',
      timeoutMinutes: 'number?',
      resumeSessionId: 'string?',
      resumeSessionLabel: 'string?',
      fireOnce: 'boolean?',
      scheduledAt: 'number?',
      baseRef: 'string?',
      requireIsolation: 'boolean?',
      requireGhAuth: 'boolean?',
    },
    capability: 'tasks.save',
    clients: ['web', 'desktop'],
    inputType: 'TaskInput',
  },
  {
    id: 'tasks.saveWebhook',
    fn: 'saveTaskWebhook',
    method: 'POST',
    path: '/api/v1/tasks/save-webhook',
    core: 'updateTaskWebhook',
    args: 'payload',
    input: {
      taskId: 'string',
      webhookIntegrationId: 'string?',
      webhookEvents: 'string[]?',
      webhookFilters: 'object?',
    },
    nullable: true,
    capability: 'tasks.saveWebhook',
    clients: ['web', 'desktop'],
    inputType:
      '{ taskId: string; webhookIntegrationId?: string; webhookEvents?: string[]; webhookFilters?: WebhookFilters }',
  },
  {
    id: 'tasks.toggle',
    fn: 'toggleTask',
    method: 'POST',
    path: '/api/v1/tasks/toggle',
    core: 'setTaskEnabled',
    args: ['id', 'enabled'],
    input: { id: 'string', enabled: 'boolean' },
    nullable: true,
    capability: 'tasks.toggle',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ id: string; enabled: boolean }',
  },
  {
    id: 'tasks.remove',
    fn: 'removeTask',
    method: 'POST',
    path: '/api/v1/tasks/remove',
    core: 'deleteTask',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'tasks.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.delete',
    fn: 'deleteTasks',
    method: 'POST',
    path: '/api/v1/tasks/delete',
    core: 'deleteTasks',
    args: ['ids'],
    input: { ids: 'string[]' },
    returnsOk: true,
    capability: 'tasks.delete',
    clients: ['web', 'desktop'],
    inputType: '{ ids: string[] }',
  },
  {
    id: 'tasks.runNow',
    fn: 'runTaskNow',
    method: 'POST',
    path: '/api/v1/tasks/run-now',
    core: 'runTaskNow',
    args: ['id'],
    input: { id: 'string' },
    capability: 'tasks.runNow',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.isolateWorkspace',
    fn: 'isolateTaskWorkspace',
    method: 'POST',
    path: '/api/v1/tasks/isolate-workspace',
    core: 'isolateTaskWorkspace',
    args: ['id'],
    input: { id: 'string' },
    capability: 'tasks.isolateWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.restoreWorkspace',
    fn: 'restoreTaskWorkspace',
    method: 'POST',
    path: '/api/v1/tasks/restore-workspace',
    core: 'restoreTaskWorkspace',
    args: ['id'],
    input: { id: 'string' },
    capability: 'tasks.restoreWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.clearWorkspaceQuarantine',
    fn: 'clearTaskWorkspaceQuarantine',
    method: 'POST',
    path: '/api/v1/tasks/clear-workspace-quarantine',
    core: 'clearTaskWorkspaceQuarantine',
    args: ['id'],
    input: { id: 'string' },
    capability: 'tasks.clearWorkspaceQuarantine',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.listRunningIds',
    fn: 'listRunningTaskIds',
    method: 'GET',
    path: '/api/v1/tasks/list-running-ids',
    core: 'listRunningTaskIds',
    args: 'none',
    input: null,
    capability: 'tasks.listRunningIds',
    clients: ['web', 'desktop'],
  },
  {
    id: 'tasks.createsFromPlan',
    fn: 'createTasksFromPlan',
    method: 'POST',
    path: '/api/v1/tasks/creates-from-plan',
    core: 'createTasksFromPlan',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string', proposals: 'array', enabled: 'boolean?' },
    capability: 'tasks.createsFromPlan',
    clients: ['web', 'desktop'],
    inputType:
      '{ runtimeId: string; workspaceId: string; proposals: PlanProposal[]; enabled?: boolean }',
  },

  // --- usage ---------------------------------------------------------------
  {
    id: 'usage.report',
    fn: 'usageReport',
    method: 'GET',
    path: '/api/v1/usage/report',
    core: 'getUsageReport',
    args: 'payload',
    input: { range: 'string?' },
    inputOptional: true,
    capability: 'usage.report',
    clients: ['web', 'desktop'],
    inputType: '{ range?: string }',
  },
  {
    id: 'usage.pressure',
    fn: 'usagePressure',
    method: 'GET',
    path: '/api/v1/usage/pressure',
    core: 'getUsagePressure',
    args: 'none',
    input: null,
    capability: 'usage.pressure',
    clients: ['web', 'desktop'],
  },

  // --- workspaces ----------------------------------------------------------
  {
    id: 'workspaces.restore',
    fn: 'restoreWorkspace',
    method: 'POST',
    path: '/api/v1/workspaces/restore',
    core: 'restoreWorkspaceById',
    args: ['workspaceId'],
    input: { workspaceId: 'string' },
    capability: 'workspaces.restore',
    clients: ['web', 'desktop'],
    inputType: '{ workspaceId: string }',
  },
  {
    id: 'workspaces.runBaseline',
    fn: 'runWorkspaceBaseline',
    method: 'POST',
    path: '/api/v1/workspaces/run-baseline',
    core: 'runWorkspaceBaseline',
    args: ['workspaceId'],
    input: { workspaceId: 'string' },
    capability: 'workspaces.runBaseline',
    clients: ['web', 'desktop'],
    inputType: '{ workspaceId: string }',
  },
  {
    id: 'workspaces.list',
    fn: 'listWorkspaces',
    method: 'GET',
    path: '/api/v1/workspaces/list',
    core: 'listWorkspaces',
    args: ['projectId'],
    input: { projectId: 'string?' },
    inputOptional: true,
    capability: 'workspaces.list',
    clients: ['web', 'desktop'],
    inputType: '{ projectId?: string }',
  },
  {
    id: 'workspaces.retrySetup',
    fn: 'retryWorkspaceSetup',
    method: 'POST',
    path: '/api/v1/workspaces/retry-setup',
    core: 'runSetup',
    args: ['id'],
    input: { id: 'string' },
    capability: 'workspaces.retrySetup',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'workspaces.archive',
    fn: 'archiveWorkspace',
    method: 'POST',
    path: '/api/v1/workspaces/archive',
    core: 'archiveWorkspace',
    args: ['id', 'force'],
    input: { id: 'string', force: 'boolean' },
    capability: 'workspaces.archive',
    clients: ['web', 'desktop'],
    inputType: '{ id: string; force: boolean }',
  },
] as const satisfies readonly Operation[]
