/** cloud operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const cloudOperations = [
  {
    id: 'cloud.status',
    fn: 'cloudStatus',
    method: 'GET',
    path: '/api/v1/cloud/status',
    core: 'getCloudStatus',
    args: 'none',
    input: null,
    capability: 'cloud.status',
    clients: ['web', 'desktop'],
  },
  {
    id: 'cloud.startLogin',
    fn: 'startCloudLogin',
    method: 'POST',
    path: '/api/v1/cloud/start-login',
    core: 'startCloudLogin',
    args: ['origin', 'next'],
    input: { origin: 'string', next: 'string?' },
    capability: 'cloud.startLogin',
    clients: ['web', 'desktop'],
    inputType: '{ origin: string; next?: string }',
  },
  {
    id: 'cloud.completeLogin',
    fn: 'completeCloudLogin',
    method: 'POST',
    path: '/api/v1/cloud/complete-login',
    core: 'completeCloudLoginAndFinish',
    args: 'payload',
    input: { code: 'string', state: 'string' },
    capability: 'cloud.completeLogin',
    clients: ['web', 'desktop'],
    inputType: '{ code: string; state: string }',
  },
  {
    id: 'cloud.providers',
    fn: 'cloudProviders',
    method: 'GET',
    path: '/api/v1/cloud/providers',
    core: 'listCloudProviders',
    args: 'none',
    input: null,
    capability: 'cloud.providers',
    clients: ['web', 'desktop'],
    summary: 'Which providers this control plane can connect. Public — no session needed.',
  },
  {
    id: 'cloud.skipOnboarding',
    fn: 'skipCloudOnboarding',
    method: 'POST',
    path: '/api/v1/cloud/skip-onboarding',
    core: 'skipCloudOnboarding',
    args: 'none',
    input: null,
    capability: 'cloud.skipOnboarding',
    clients: ['web', 'desktop'],
  },
  {
    id: 'cloud.signOut',
    fn: 'signOutCloud',
    method: 'POST',
    path: '/api/v1/cloud/sign-out',
    core: 'signOutAndDisconnect',
    args: 'none',
    input: null,
    returnsOk: true,
    capability: 'cloud.signOut',
    clients: ['web', 'desktop'],
  },
  {
    id: 'cloud.startHostedConnect',
    fn: 'startHostedConnect',
    method: 'POST',
    path: '/api/v1/cloud/start-hosted-connect',
    core: 'startHostedConnect',
    args: 'payload',
    input: { provider: 'string', origin: 'string' },
    capability: 'cloud.startHostedConnect',
    clients: ['web', 'desktop'],
    inputType: '{ provider: string; origin: string }',
  },
  {
    id: 'cloud.completeHostedConnect',
    fn: 'completeHostedConnect',
    method: 'POST',
    path: '/api/v1/cloud/complete-hosted-connect',
    core: 'completeHostedConnect',
    args: 'payload',
    input: {
      provider: 'string',
      cloudConnectionId: 'string',
      state: 'string?',
      siteUrl: 'string?',
      accountName: 'string?',
    },
    capability: 'cloud.completeHostedConnect',
    clients: ['web', 'desktop'],
    inputType:
      '{ provider: string; cloudConnectionId: string; state?: string; siteUrl?: string; accountName?: string }',
  },
  {
    id: 'cloud.listHostedConnections',
    fn: 'listHostedConnections',
    method: 'GET',
    path: '/api/v1/cloud/list-hosted-connections',
    core: 'listHostedConnections',
    args: 'none',
    input: null,
    capability: 'cloud.listHostedConnections',
    clients: ['web', 'desktop'],
  },
] as const satisfies readonly Operation[]
