/** devices operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const devicesOperations = [
  {
    id: 'devices.mobileStatus',
    fn: 'mobileStatus',
    method: 'GET',
    path: '/api/v1/devices/mobile-status',
    core: 'mobileStatus',
    args: 'none',
    input: null,
    capability: 'devices.mobileStatus',
    clients: ['web', 'desktop'],
  },
  {
    id: 'devices.createPairingCode',
    fn: 'createPairingCode',
    method: 'POST',
    path: '/api/v1/devices/create-pairing-code',
    core: 'createPairingCode',
    args: 'none',
    input: null,
    capability: 'devices.createPairingCode',
    clients: ['web', 'desktop'],
  },
  {
    id: 'devices.cancelPairing',
    fn: 'cancelPairing',
    method: 'POST',
    path: '/api/v1/devices/cancel-pairing',
    core: 'cancelPairing',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'devices.cancelPairing',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'devices.revoke',
    fn: 'revokeDevice',
    method: 'POST',
    path: '/api/v1/devices/revoke',
    core: 'revokeDevice',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'devices.revoke',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'devices.remove',
    fn: 'removeDevice',
    method: 'POST',
    path: '/api/v1/devices/remove',
    core: 'deleteDevice',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'devices.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
] as const satisfies readonly Operation[]
