/** files operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const filesOperations = [
  {
    id: 'files.listWorkspace',
    fn: 'listWorkspaceFiles',
    method: 'GET',
    path: '/api/v1/files/list-workspace',
    core: 'listWorkspaceFiles',
    args: 'payload',
    input: { runId: 'string', dir: 'string?' },
    capability: 'runs.files',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string; dir?: string }',
  },
  {
    id: 'files.readWorkspace',
    fn: 'readWorkspaceFile',
    method: 'GET',
    path: '/api/v1/files/read-workspace',
    core: 'readWorkspaceFile',
    args: 'payload',
    input: { runId: 'string', path: 'string' },
    capability: 'runs.files',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string; path: string }',
  },
  {
    id: 'files.writeWorkspace',
    fn: 'writeWorkspaceFile',
    method: 'POST',
    path: '/api/v1/files/write-workspace',
    core: 'writeWorkspaceFile',
    args: 'payload',
    input: { runId: 'string', path: 'string', content: 'string' },
    capability: 'files.writeWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; path: string; content: string }',
  },
  {
    id: 'files.restoreWorkspace',
    fn: 'restoreWorkspaceFile',
    method: 'POST',
    path: '/api/v1/files/restore-workspace',
    core: 'restoreWorkspaceFile',
    args: 'payload',
    input: { runId: 'string', path: 'string', content: 'string' },
    capability: 'files.restoreWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; path: string; content: string }',
  },
  {
    id: 'files.saveAttachment',
    fn: 'saveAttachment',
    method: 'POST',
    path: '/api/v1/files/save-attachment',
    core: 'saveWorkspaceAttachment',
    args: 'payload',
    input: {
      workspaceId: 'string',
      runId: 'string?',
      name: 'string',
      mimeType: 'string',
      data: 'string',
    },
    capability: 'files.saveAttachment',
    clients: ['web', 'desktop'],
    inputType:
      '{ workspaceId: string; runId?: string; name: string; mimeType: string; data: string }',
    summary: 'Upload a composer image; `data` is raw base64 without the data-URL prefix.',
  },
] as const satisfies readonly Operation[]
