/** git operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const gitOperations = [
  {
    id: 'git.getFileDiff',
    fn: 'getFileDiff',
    method: 'GET',
    path: '/api/v1/git/get-file-diff',
    core: 'getFileDiff',
    args: 'payload',
    input: { runId: 'string', path: 'string', whole: 'boolean?' },
    capability: 'runs.diff',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string; path: string; whole?: boolean }',
  },
  {
    id: 'git.commitChanges',
    fn: 'commitChanges',
    method: 'POST',
    path: '/api/v1/git/commit-changes',
    core: 'commitChanges',
    args: 'payload',
    input: { runId: 'string', message: 'string', paths: 'string[]?' },
    capability: 'git.commitChanges',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; message: string; paths?: string[] }',
  },
  {
    id: 'git.pushChanges',
    fn: 'pushChanges',
    method: 'POST',
    path: '/api/v1/git/push-changes',
    core: 'pushChanges',
    args: 'payload',
    input: { runId: 'string' },
    capability: 'git.pushChanges',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'git.discardChanges',
    fn: 'discardChanges',
    method: 'POST',
    path: '/api/v1/git/discard-changes',
    core: 'discardChanges',
    args: 'payload',
    input: { runId: 'string', paths: 'string[]?', resetCommits: 'boolean?' },
    capability: 'git.discardChanges',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; paths?: string[]; resetCommits?: boolean }',
  },
  {
    id: 'git.discardHunk',
    fn: 'discardHunk',
    method: 'POST',
    path: '/api/v1/git/discard-hunk',
    core: 'discardHunk',
    args: 'payload',
    input: { runId: 'string', path: 'string', hunkIndex: 'number' },
    capability: 'git.discardHunk',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; path: string; hunkIndex: number }',
  },
  {
    id: 'git.createBranch',
    fn: 'createBranch',
    method: 'POST',
    path: '/api/v1/git/create-branch',
    core: 'createBranch',
    args: 'payload',
    input: { runId: 'string', name: 'string' },
    capability: 'git.createBranch',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; name: string }',
  },
  {
    id: 'git.openPullRequest',
    fn: 'openPullRequest',
    method: 'POST',
    path: '/api/v1/git/open-pull-request',
    core: 'openPullRequest',
    args: 'payload',
    input: { runId: 'string', title: 'string', body: 'string', base: 'string?' },
    capability: 'git.openPullRequest',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; title: string; body: string; base?: string }',
  },
  {
    id: 'git.shipRun',
    fn: 'shipRun',
    method: 'POST',
    path: '/api/v1/git/ship-run',
    core: 'shipRun',
    args: 'payload',
    input: { runId: 'string', base: 'string?', skipPlan: 'boolean?' },
    capability: 'git.shipRun',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string; base?: string; skipPlan?: boolean }',
  },
  {
    id: 'git.listProjectBranches',
    fn: 'listProjectBranches',
    method: 'GET',
    path: '/api/v1/git/list-project-branches',
    core: 'listProjectBranches',
    args: ['projectId'],
    input: { projectId: 'string' },
    capability: 'git.listProjectBranches',
    clients: ['web', 'desktop'],
    inputType: '{ projectId: string }',
  },
] as const satisfies readonly Operation[]
