/** integrations operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const integrationsOperations = [
  {
    id: 'integrations.listProviders',
    fn: 'listIntegrationProviders',
    method: 'GET',
    path: '/api/v1/integrations/list-providers',
    core: 'listProviderCatalog',
    args: 'none',
    input: null,
    capability: 'integrations.listProviders',
    clients: ['web', 'desktop'],
  },
  {
    id: 'integrations.list',
    fn: 'listIntegrations',
    method: 'GET',
    path: '/api/v1/integrations/list',
    core: 'listIntegrations',
    args: 'none',
    input: null,
    capability: 'integrations.list',
    clients: ['web', 'desktop'],
  },
  {
    id: 'integrations.get',
    fn: 'getIntegration',
    method: 'GET',
    path: '/api/v1/integrations/get',
    core: 'getIntegrationPublic',
    args: ['id'],
    input: { id: 'string' },
    nullable: true,
    capability: 'integrations.get',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'integrations.create',
    fn: 'createIntegration',
    method: 'POST',
    path: '/api/v1/integrations/create',
    core: 'createIntegration',
    args: 'payload',
    input: { provider: 'string' },
    capability: 'integrations.create',
    clients: ['web', 'desktop'],
    inputType: 'CreateIntegrationInput',
  },
  {
    id: 'integrations.update',
    fn: 'updateIntegration',
    method: 'POST',
    path: '/api/v1/integrations/update',
    core: 'updateIntegration',
    args: 'payload',
    input: { id: 'string' },
    capability: 'integrations.update',
    clients: ['web', 'desktop'],
    inputType: 'UpdateIntegrationInput',
  },
  {
    id: 'integrations.listWebhookDeliveries',
    fn: 'listWebhookDeliveries',
    method: 'GET',
    path: '/api/v1/integrations/list-webhook-deliveries',
    core: 'listWebhookDeliveries',
    args: 'payload',
    input: { integrationId: 'string?', limit: 'number?' },
    inputOptional: true,
    capability: 'integrations.listWebhookDeliveries',
    clients: ['web', 'desktop'],
    inputType: '{ integrationId?: string; limit?: number }',
  },
  {
    id: 'integrations.getAutomationSetupContext',
    fn: 'getAutomationSetupContext',
    method: 'GET',
    path: '/api/v1/integrations/get-automation-setup-context',
    core: 'getAutomationSetupContext',
    args: 'none',
    input: null,
    capability: 'integrations.getAutomationSetupContext',
    clients: ['web', 'desktop'],
  },
  {
    id: 'integrations.createAutomation',
    fn: 'createIntegrationAutomation',
    method: 'POST',
    path: '/api/v1/integrations/create-automation',
    core: 'createIntegrationAutomation',
    args: 'payload',
    input: {
      integrationId: 'string',
      workspaceId: 'string',
      runtimeId: 'string',
      trigger: 'object?',
      events: 'string[]?',
      name: 'string?',
      prompt: 'string?',
      enabled: 'boolean?',
    },
    capability: 'integrations.createAutomation',
    clients: ['web', 'desktop'],
    inputType: 'CreateIntegrationAutomationInput',
    summary: 'Bind a connected integration to a workspace + runtime so deliveries run.',
  },
  {
    id: 'integrations.disconnectHosted',
    fn: 'disconnectHostedIntegration',
    method: 'POST',
    path: '/api/v1/integrations/disconnect-hosted',
    core: 'disconnectHostedIntegration',
    args: ['integrationId'],
    input: { integrationId: 'string' },
    capability: 'integrations.disconnectHosted',
    clients: ['web', 'desktop'],
    inputType: '{ integrationId: string }',
  },
  {
    id: 'integrations.ingestTestEvent',
    fn: 'ingestTestEvent',
    method: 'POST',
    path: '/api/v1/integrations/ingest-test-event',
    core: 'ingestTestEvent',
    args: ['integrationId'],
    input: { integrationId: 'string' },
    capability: 'integrations.ingestTestEvent',
    clients: ['web', 'desktop'],
    inputType: '{ integrationId: string }',
  },
] as const satisfies readonly Operation[]
