/** mcp operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const mcpOperations = [
  {
    id: 'mcp.getConfig',
    fn: 'getMcpConfig',
    method: 'GET',
    path: '/api/v1/mcp/get-config',
    core: 'getMcpConfig',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string?' },
    capability: 'mcp.getConfig',
    clients: ['web', 'desktop'],
    inputType: '{ runtimeId: string; workspaceId?: string }',
  },
  {
    id: 'mcp.saveServer',
    fn: 'saveMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/save-server',
    core: 'saveMcpServerConfig',
    args: 'payload',
    input: {
      runtimeId: 'string',
      workspaceId: 'string?',
      targetId: 'string',
      server: 'object',
      previousName: 'string?',
    },
    capability: 'mcp.saveServer',
    clients: ['web', 'desktop'],
    inputType:
      '{ runtimeId: string; workspaceId?: string; targetId: string; server: McpServerConfig; previousName?: string }',
  },
  {
    id: 'mcp.removeServer',
    fn: 'removeMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/remove-server',
    core: 'removeMcpServerConfig',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string?', targetId: 'string', name: 'string' },
    capability: 'mcp.removeServer',
    clients: ['web', 'desktop'],
    inputType: '{ runtimeId: string; workspaceId?: string; targetId: string; name: string }',
  },
  {
    id: 'mcp.getShared',
    fn: 'getSharedMcp',
    method: 'GET',
    path: '/api/v1/mcp/get-shared',
    core: 'getSharedMcpConfig',
    args: 'none',
    input: null,
    capability: 'mcp.getShared',
    clients: ['web', 'desktop'],
  },
  {
    id: 'mcp.saveSharedServer',
    fn: 'saveSharedMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/save-shared-server',
    core: 'saveSharedMcpServerConfig',
    args: 'payload',
    input: { server: 'object', previousName: 'string?', force: 'boolean?' },
    capability: 'mcp.saveSharedServer',
    clients: ['web', 'desktop'],
    inputType: '{ server: McpServerConfig; previousName?: string; force?: boolean }',
  },
  {
    id: 'mcp.removeSharedServer',
    fn: 'removeSharedMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/remove-shared-server',
    core: 'removeSharedMcpServerConfig',
    args: 'payload',
    input: { name: 'string', scope: 'string?' },
    capability: 'mcp.removeSharedServer',
    clients: ['web', 'desktop'],
    inputType: "{ name: string; scope?: 'registry' | 'everywhere' }",
  },
  {
    id: 'mcp.discoverServers',
    fn: 'discoverMcpServers',
    method: 'GET',
    path: '/api/v1/mcp/discover-servers',
    core: 'discoverMcpServersConfig',
    args: 'none',
    input: null,
    capability: 'mcp.discoverServers',
    clients: ['web', 'desktop'],
  },
  {
    id: 'mcp.importServers',
    fn: 'importMcpServers',
    method: 'POST',
    path: '/api/v1/mcp/import-servers',
    core: 'importMcpServersConfig',
    args: 'payload',
    input: { choices: 'array' },
    capability: 'mcp.importServers',
    clients: ['web', 'desktop'],
    inputType: '{ choices: { name: string; fromTargetId: string }[] }',
  },
  {
    id: 'mcp.getOAuthStatus',
    fn: 'getMcpOAuthStatus',
    method: 'GET',
    path: '/api/v1/mcp/get-oauth-status',
    core: 'getMcpOAuthStatus',
    args: 'none',
    input: null,
    capability: 'mcp.getOAuthStatus',
    clients: ['web', 'desktop'],
  },
  {
    id: 'mcp.startOAuth',
    fn: 'startMcpOAuth',
    method: 'POST',
    path: '/api/v1/mcp/start-oauth',
    core: 'startMcpOAuth',
    args: 'payload',
    input: { name: 'string', redirectUri: 'string' },
    capability: 'mcp.startOAuth',
    clients: ['web', 'desktop'],
    inputType: '{ name: string; redirectUri: string }',
  },
  {
    id: 'mcp.disconnectServer',
    fn: 'disconnectMcpServer',
    method: 'POST',
    path: '/api/v1/mcp/disconnect-server',
    core: 'disconnectMcpServer',
    args: 'payload',
    input: { name: 'string' },
    capability: 'mcp.disconnectServer',
    clients: ['web', 'desktop'],
    inputType: '{ name: string }',
  },
  {
    id: 'mcp.syncShared',
    fn: 'syncSharedMcp',
    method: 'POST',
    path: '/api/v1/mcp/sync-shared',
    core: 'syncSharedMcpConfig',
    args: 'payload',
    input: { force: 'boolean?' },
    inputOptional: true,
    capability: 'mcp.syncShared',
    clients: ['web', 'desktop'],
    inputType: '{ force?: boolean }',
  },
] as const satisfies readonly Operation[]
