/** notifications operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const notificationsOperations = [
  {
    id: 'notifications.listNotifiers',
    fn: 'listNotifiers',
    method: 'GET',
    path: '/api/v1/notifications/list-notifiers',
    core: 'listNotifiers',
    args: 'none',
    input: null,
    capability: 'notifications.listNotifiers',
    clients: ['web', 'desktop'],
  },
  {
    id: 'notifications.saveNotifier',
    fn: 'saveNotifier',
    method: 'POST',
    path: '/api/v1/notifications/save-notifier',
    core: 'upsertNotifier',
    args: 'payload',
    input: { kind: 'string', name: 'string', target: 'string?', enabled: 'boolean' },
    capability: 'notifications.saveNotifier',
    clients: ['web', 'desktop'],
    inputType: 'NotifierInput',
  },
  {
    id: 'notifications.removeNotifier',
    fn: 'removeNotifier',
    method: 'POST',
    path: '/api/v1/notifications/remove-notifier',
    core: 'deleteNotifier',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'notifications.removeNotifier',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'notifications.testNotifier',
    fn: 'testNotifier',
    method: 'POST',
    path: '/api/v1/notifications/test-notifier',
    core: 'testNotifier',
    args: ['id'],
    input: { id: 'string' },
    capability: 'notifications.testNotifier',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'notifications.listDeliveries',
    fn: 'listNotificationDeliveries',
    method: 'GET',
    path: '/api/v1/notifications/list-deliveries',
    core: 'listNotificationDeliveries',
    args: 'payload',
    input: { notifierId: 'string?', limit: 'number?' },
    inputOptional: true,
    capability: 'notifications.listDeliveries',
    clients: ['web', 'desktop'],
    inputType: '{ notifierId?: string; limit?: number }',
  },
] as const satisfies readonly Operation[]
