/** projects operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const projectsOperations = [
  {
    id: 'projects.list',
    fn: 'listProjects',
    method: 'GET',
    path: '/api/v1/projects/list',
    core: 'listProjects',
    args: 'none',
    input: null,
    capability: 'projects.list',
    clients: ['web', 'desktop'],
  },
  {
    id: 'projects.listLocalDirectories',
    fn: 'listLocalDirectories',
    method: 'GET',
    path: '/api/v1/projects/list-local-directories',
    core: 'listLocalDirectories',
    args: ['dir', 'showHidden'],
    input: { dir: 'string?', showHidden: 'boolean?' },
    inputOptional: true,
    capability: 'projects.listLocalDirectories',
    clients: ['web', 'desktop'],
    inputType: '{ dir?: string; showHidden?: boolean }',
  },
  {
    id: 'projects.listLocalPlaces',
    fn: 'listLocalPlaces',
    method: 'GET',
    path: '/api/v1/projects/list-local-places',
    core: 'listLocalPlaces',
    args: 'none',
    input: null,
    capability: 'projects.listLocalPlaces',
    clients: ['web', 'desktop'],
  },
  {
    id: 'projects.createLocalFolder',
    fn: 'createLocalFolder',
    method: 'POST',
    path: '/api/v1/projects/create-local-folder',
    core: 'createLocalFolder',
    args: 'payload',
    input: { parent: 'string?', name: 'string' },
    capability: 'projects.createLocalFolder',
    clients: ['web', 'desktop'],
    inputType: '{ parent?: string; name: string }',
  },
  {
    id: 'projects.add',
    fn: 'addProject',
    method: 'POST',
    path: '/api/v1/projects/add',
    core: 'addProject',
    args: 'payload',
    input: {
      mode: 'string',
      url: 'string?',
      path: 'string?',
      name: 'string?',
      setupCommand: 'string?',
    },
    capability: 'projects.add',
    clients: ['web', 'desktop'],
    inputType:
      "{ mode: 'clone' | 'register'; url?: string; path?: string; name?: string; setupCommand?: string }",
  },
  {
    id: 'projects.update',
    fn: 'updateProject',
    method: 'POST',
    path: '/api/v1/projects/update',
    core: 'updateProject',
    args: 'payload',
    input: {
      id: 'string',
      name: 'string?',
      setupCommand: 'string?',
      defaultBranch: 'string?',
      checks: 'array?',
    },
    capability: 'projects.update',
    clients: ['web', 'desktop'],
    inputType:
      '{ id: string; name?: string; setupCommand?: string; defaultBranch?: string; checks?: CheckDef[] }',
  },
  {
    id: 'projects.suggestChecks',
    fn: 'suggestProjectChecks',
    method: 'POST',
    path: '/api/v1/projects/suggest-checks',
    core: 'suggestProjectChecks',
    args: ['id'],
    input: { id: 'string' },
    capability: 'projects.suggestChecks',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
    summary: 'Checks Open Run would propose for this repo, from its package.json scripts.',
  },
  {
    id: 'projects.remove',
    fn: 'removeProject',
    method: 'POST',
    path: '/api/v1/projects/remove',
    core: 'deleteProject',
    args: ['id', 'deleteFiles'],
    input: { id: 'string', deleteFiles: 'boolean' },
    returnsOk: true,
    capability: 'projects.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string; deleteFiles: boolean }',
  },
] as const satisfies readonly Operation[]
