/** runs operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const runsOperations = [
  {
    id: 'runs.listNativeSessions',
    fn: 'listNativeSessions',
    method: 'GET',
    path: '/api/v1/runs/list-native-sessions',
    core: 'listNativeSessions',
    args: 'payload',
    input: {
      workspaceId: 'string?',
      allWorkspaces: 'boolean?',
      kind: 'string?',
      offset: 'number?',
      limit: 'number?',
    },
    capability: 'runs.listNativeSessions',
    clients: ['web', 'desktop'],
    inputType:
      "{ workspaceId?: string; allWorkspaces?: boolean; kind?: 'claude' | 'codex' | 'grok' | 'antigravity'; offset?: number; limit?: number }",
  },
  {
    id: 'runs.list',
    fn: 'listRuns',
    method: 'GET',
    path: '/api/v1/runs/list',
    core: 'listRuns',
    args: 'payload',
    input: { taskId: 'string?', limit: 'number?', offset: 'number?', includeArchived: 'boolean?' },
    inputOptional: true,
    capability: 'runs.list',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ taskId?: string; limit?: number; offset?: number; includeArchived?: boolean }',
  },
  {
    id: 'runs.listConversationNavigation',
    fn: 'listConversationNavigationRuns',
    method: 'GET',
    path: '/api/v1/runs/list-conversation-navigation',
    core: 'listConversationNavigationRuns',
    args: 'none',
    input: null,
    capability: 'runs.listConversationNavigation',
    clients: ['web', 'desktop'],
  },
  {
    id: 'runs.count',
    fn: 'countRuns',
    method: 'GET',
    path: '/api/v1/runs/count',
    core: 'countRuns',
    args: 'payload',
    input: { taskId: 'string?', includeArchived: 'boolean?' },
    inputOptional: true,
    capability: 'runs.count',
    clients: ['web', 'desktop'],
    inputType: '{ taskId?: string; includeArchived?: boolean }',
  },
  {
    id: 'runs.listChecks',
    fn: 'listRunChecks',
    method: 'GET',
    path: '/api/v1/runs/list-checks',
    core: 'listRunChecks',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.listChecks',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.reRunChecks',
    fn: 'rerunRunChecks',
    method: 'POST',
    path: '/api/v1/runs/re-run-checks',
    core: 'rerunRunChecks',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.reRunChecks',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.get',
    fn: 'getRun',
    method: 'GET',
    path: '/api/v1/runs/get',
    core: 'getRun',
    args: ['id'],
    input: { id: 'string' },
    nullable: true,
    capability: 'runs.read',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ id: string }',
  },
  {
    id: 'runs.cancel',
    fn: 'cancelRun',
    method: 'POST',
    path: '/api/v1/runs/cancel',
    core: 'cancelRun',
    args: ['id'],
    input: { id: 'string' },
    nullable: true,
    capability: 'runs.cancel',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ id: string }',
  },
  {
    id: 'runs.markRead',
    fn: 'markRunRead',
    method: 'POST',
    path: '/api/v1/runs/mark-read',
    core: 'markRunRead',
    args: ['id'],
    input: { id: 'string' },
    capability: 'runs.markRead',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'runs.remove',
    fn: 'removeRun',
    method: 'POST',
    path: '/api/v1/runs/remove',
    core: 'deleteRun',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'runs.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'runs.delete',
    fn: 'deleteRuns',
    method: 'POST',
    path: '/api/v1/runs/delete',
    core: 'deleteRuns',
    args: ['ids'],
    input: { ids: 'string[]' },
    returnsOk: true,
    capability: 'runs.delete',
    clients: ['web', 'desktop'],
    inputType: '{ ids: string[] }',
  },
  {
    id: 'runs.getLatestForWorkspace',
    fn: 'getLatestRunForWorkspace',
    method: 'GET',
    path: '/api/v1/runs/get-latest-for-workspace',
    core: 'getLatestRunForWorkspace',
    args: ['workspaceId'],
    input: { workspaceId: 'string' },
    capability: 'runs.getLatestForWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ workspaceId: string }',
  },
  {
    id: 'runs.getLatestForProject',
    fn: 'getLatestRunForProject',
    method: 'GET',
    path: '/api/v1/runs/get-latest-for-project',
    core: 'getLatestRunForProject',
    args: ['projectId'],
    input: { projectId: 'string' },
    capability: 'runs.getLatestForProject',
    clients: ['web', 'desktop'],
    inputType: '{ projectId: string }',
  },
  {
    id: 'runs.startOptions',
    fn: 'startRunOptions',
    method: 'GET',
    path: '/api/v1/runs/start-options',
    core: 'startRunOptions',
    args: 'none',
    input: null,
    capability: 'runs.startOptions',
    clients: ['web', 'desktop', 'mobile'],
  },
  {
    id: 'runs.repeat',
    fn: 'repeatRun',
    method: 'POST',
    path: '/api/v1/runs/repeat',
    core: 'repeatRun',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.create',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.startChat',
    fn: 'startChat',
    method: 'POST',
    path: '/api/v1/runs/start-chat',
    core: 'startChat',
    args: 'payload',
    input: {
      workspaceId: 'string',
      runtimeId: 'string',
      prompt: 'string',
      model: 'string?',
      effort: 'string?',
      runtimeMode: 'string?',
      resumeSessionId: 'string?',
      resumeSessionLabel: 'string?',
    },
    capability: 'runs.create',
    clients: ['web', 'desktop', 'mobile'],
    inputType:
      '{ workspaceId: string; runtimeId: string; prompt: string; model?: string; effort?: string; runtimeMode?: string; resumeSessionId?: string; resumeSessionLabel?: string }',
  },
  {
    id: 'runs.openNativeChat',
    fn: 'openNativeChat',
    method: 'POST',
    path: '/api/v1/runs/open-native-chat',
    core: 'openNativeChat',
    args: 'payload',
    input: {
      workspaceId: 'string',
      runtimeId: 'string',
      sessionId: 'string',
      sessionLabel: 'string?',
      model: 'string?',
      effort: 'string?',
      runtimeMode: 'string?',
    },
    capability: 'runs.openNativeChat',
    clients: ['web', 'desktop'],
    inputType:
      '{ workspaceId: string; runtimeId: string; sessionId: string; sessionLabel?: string; model?: string; effort?: string; runtimeMode?: string }',
  },
  {
    id: 'runs.getConversation',
    fn: 'getConversation',
    method: 'GET',
    path: '/api/v1/runs/get-conversation',
    core: 'getConversation',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.read',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.getWorkspace',
    fn: 'getRunWorkspace',
    method: 'GET',
    path: '/api/v1/runs/get-workspace',
    core: 'getRunWorkspace',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.diff',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.getPullRequest',
    fn: 'getRunPullRequest',
    method: 'GET',
    path: '/api/v1/runs/get-pull-request',
    core: 'getRunPullRequest',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.getPullRequest',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
  },
  {
    id: 'runs.postMessage',
    fn: 'postMessage',
    method: 'POST',
    path: '/api/v1/runs/post-message',
    core: 'postMessage',
    args: 'payload',
    input: {
      runId: 'string',
      prompt: 'string',
      runtimeId: 'string?',
      model: 'string?',
      effort: 'string?',
      runtimeMode: 'string?',
      userMessageId: 'string?',
      assistantMessageId: 'string?',
      force: 'boolean?',
    },
    capability: 'runs.message',
    clients: ['web', 'desktop', 'mobile'],
    inputType:
      '{ runId: string; prompt: string; runtimeId?: string; model?: string; effort?: string; runtimeMode?: string; userMessageId?: string; assistantMessageId?: string; force?: boolean }',
  },
  {
    id: 'runs.dequeueMessage',
    fn: 'dequeueMessage',
    method: 'POST',
    path: '/api/v1/runs/dequeue-message',
    core: 'dequeueFollowUp',
    args: 'payload',
    input: { id: 'string' },
    capability: 'runs.dequeueMessage',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
    summary: 'Drop one follow-up waiting on the current turn.',
  },
  {
    id: 'runs.clearQueuedMessages',
    fn: 'clearQueuedMessages',
    method: 'POST',
    path: '/api/v1/runs/clear-queued-messages',
    core: 'clearQueuedFollowUps',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.clearQueuedMessages',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
    summary: 'Drop every follow-up waiting on a run.',
  },
  {
    id: 'runs.flushQueuedMessages',
    fn: 'flushQueuedMessages',
    method: 'POST',
    path: '/api/v1/runs/flush-queued-messages',
    core: 'flushQueuedFollowUps',
    args: ['runId'],
    input: { runId: 'string' },
    capability: 'runs.flushQueuedMessages',
    clients: ['web', 'desktop'],
    inputType: '{ runId: string }',
    summary: 'Deliver the next queued follow-up on a run that is no longer working.',
  },
  {
    id: 'runs.answerApproval',
    fn: 'answerApproval',
    method: 'POST',
    path: '/api/v1/runs/answer-approval',
    core: 'answerApproval',
    args: 'payload',
    input: {
      runId: 'string',
      requestId: 'string',
      optionId: 'string?',
      decision: 'string?',
      message: 'string?',
    },
    capability: 'approvals.answer',
    clients: ['web', 'desktop', 'mobile'],
    inputType:
      "{ runId: string; requestId: string; optionId?: string; decision?: 'allow' | 'deny'; message?: string }",
    summary:
      'Answer a pending tool-approval on a supervised run (allow/deny). The run detail UI calls this from the approval prompt; unanswered requests auto-deny on a timeout in the executor.',
  },
] as const satisfies readonly Operation[]
