/** runtimes operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const runtimesOperations = [
  {
    id: 'runtimes.list',
    fn: 'listRuntimes',
    method: 'GET',
    path: '/api/v1/runtimes/list',
    core: 'listRuntimesWithStatus',
    args: 'none',
    input: null,
    capability: 'runtimes.list',
    clients: ['web', 'desktop'],
  },
  {
    id: 'runtimes.listPresetBins',
    fn: 'listPresetBins',
    method: 'GET',
    path: '/api/v1/runtimes/list-preset-bins',
    core: 'listPresetBinStatus',
    args: 'none',
    input: null,
    capability: 'runtimes.listPresetBins',
    clients: ['web', 'desktop'],
  },
  {
    id: 'runtimes.save',
    fn: 'saveRuntime',
    method: 'POST',
    path: '/api/v1/runtimes/save',
    core: 'upsertRuntime',
    args: 'payload',
    input: { label: 'string?', bin: 'string?' },
    inputOptional: true,
    capability: 'runtimes.save',
    clients: ['web', 'desktop'],
    inputType: 'RuntimeInput',
  },
  {
    id: 'runtimes.previewCommand',
    fn: 'previewCommand',
    method: 'POST',
    path: '/api/v1/runtimes/preview-command',
    core: 'previewRuntimeCommand',
    args: 'payload',
    input: { runtimeId: 'string?', bin: 'string?' },
    inputOptional: true,
    capability: 'runtimes.previewCommand',
    clients: ['web', 'desktop'],
    inputType: 'PreviewCommandInput',
    summary:
      'Resolve the exact argv a runtime draft would spawn — no run row, no process. POST because the Runtimes editor previews an unsaved template.',
  },
  {
    id: 'runtimes.previewCommandFor',
    fn: 'previewCommandForRuntime',
    method: 'POST',
    path: '/api/v1/runtimes/preview-command-for',
    core: 'previewRuntimeCommandById',
    args: 'payload',
    input: {
      runtimeId: 'string',
      workspaceId: 'string?',
      model: 'string?',
      effort: 'string?',
      runtimeMode: 'string?',
      isFollowUp: 'boolean?',
    },
    capability: 'runtimes.previewCommandFor',
    clients: ['web', 'desktop'],
    inputType:
      '{ runtimeId: string; workspaceId?: string; model?: string; effort?: string; runtimeMode?: string; isFollowUp?: boolean }',
    summary: 'Same preview for a saved runtime, by id (tooling / non-UI callers).',
  },
  {
    id: 'runtimes.remove',
    fn: 'removeRuntime',
    method: 'POST',
    path: '/api/v1/runtimes/remove',
    core: 'deleteRuntime',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'runtimes.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
] as const satisfies readonly Operation[]
