/** tasks operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const tasksOperations = [
  {
    id: 'tasks.list',
    fn: 'listTasks',
    method: 'GET',
    path: '/api/v1/tasks/list',
    core: 'listTasks',
    args: 'none',
    input: null,
    capability: 'tasks.list',
    clients: ['web', 'desktop', 'mobile'],
  },
  {
    id: 'tasks.get',
    fn: 'getTask',
    method: 'GET',
    path: '/api/v1/tasks/get',
    core: 'getTask',
    args: ['id'],
    input: { id: 'string' },
    nullable: true,
    capability: 'tasks.get',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.save',
    fn: 'saveTask',
    method: 'POST',
    path: '/api/v1/tasks/save',
    core: 'upsertTask',
    args: 'payload',
    input: {
      id: 'string?',
      name: 'string',
      description: 'string',
      runtimeId: 'string',
      prompt: 'string',
      cwd: 'string',
      workspaceId: 'string',
      cron: 'string',
      enabled: 'boolean',
      model: 'string?',
      effort: 'string?',
      webhookIntegrationId: 'string?',
      webhookEvents: 'string[]?',
      webhookFilters: 'object?',
      verifyEnabled: 'boolean?',
      maxRepairAttempts: 'number?',
      timeoutMinutes: 'number?',
      resumeSessionId: 'string?',
      resumeSessionLabel: 'string?',
      fireOnce: 'boolean?',
      scheduledAt: 'number?',
      baseRef: 'string?',
      requireIsolation: 'boolean?',
      requireGhAuth: 'boolean?',
    },
    capability: 'tasks.save',
    clients: ['web', 'desktop'],
    inputType: 'TaskInput',
  },
  {
    id: 'tasks.saveWebhook',
    fn: 'saveTaskWebhook',
    method: 'POST',
    path: '/api/v1/tasks/save-webhook',
    core: 'updateTaskWebhook',
    args: 'payload',
    input: {
      taskId: 'string',
      webhookIntegrationId: 'string?',
      webhookEvents: 'string[]?',
      webhookFilters: 'object?',
    },
    nullable: true,
    capability: 'tasks.saveWebhook',
    clients: ['web', 'desktop'],
    inputType:
      '{ taskId: string; webhookIntegrationId?: string; webhookEvents?: string[]; webhookFilters?: WebhookFilters }',
  },
  {
    id: 'tasks.toggle',
    fn: 'toggleTask',
    method: 'POST',
    path: '/api/v1/tasks/toggle',
    core: 'setTaskEnabled',
    args: ['id', 'enabled'],
    input: { id: 'string', enabled: 'boolean' },
    nullable: true,
    capability: 'tasks.toggle',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ id: string; enabled: boolean }',
  },
  {
    id: 'tasks.remove',
    fn: 'removeTask',
    method: 'POST',
    path: '/api/v1/tasks/remove',
    core: 'deleteTask',
    args: ['id'],
    input: { id: 'string' },
    returnsOk: true,
    capability: 'tasks.remove',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.delete',
    fn: 'deleteTasks',
    method: 'POST',
    path: '/api/v1/tasks/delete',
    core: 'deleteTasks',
    args: ['ids'],
    input: { ids: 'string[]' },
    returnsOk: true,
    capability: 'tasks.delete',
    clients: ['web', 'desktop'],
    inputType: '{ ids: string[] }',
  },
  {
    id: 'tasks.runNow',
    fn: 'runTaskNow',
    method: 'POST',
    path: '/api/v1/tasks/run-now',
    core: 'runTaskNow',
    args: ['id'],
    input: { id: 'string' },
    capability: 'tasks.runNow',
    clients: ['web', 'desktop', 'mobile'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.isolateWorkspace',
    fn: 'isolateTaskWorkspace',
    method: 'POST',
    path: '/api/v1/tasks/isolate-workspace',
    core: 'isolateTaskWorkspace',
    args: ['id'],
    input: { id: 'string' },
    capability: 'tasks.isolateWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.restoreWorkspace',
    fn: 'restoreTaskWorkspace',
    method: 'POST',
    path: '/api/v1/tasks/restore-workspace',
    core: 'restoreTaskWorkspace',
    args: ['id'],
    input: { id: 'string' },
    capability: 'tasks.restoreWorkspace',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.clearWorkspaceQuarantine',
    fn: 'clearTaskWorkspaceQuarantine',
    method: 'POST',
    path: '/api/v1/tasks/clear-workspace-quarantine',
    core: 'clearTaskWorkspaceQuarantine',
    args: ['id'],
    input: { id: 'string' },
    capability: 'tasks.clearWorkspaceQuarantine',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'tasks.listRunningIds',
    fn: 'listRunningTaskIds',
    method: 'GET',
    path: '/api/v1/tasks/list-running-ids',
    core: 'listRunningTaskIds',
    args: 'none',
    input: null,
    capability: 'tasks.listRunningIds',
    clients: ['web', 'desktop'],
  },
  {
    id: 'tasks.createsFromPlan',
    fn: 'createTasksFromPlan',
    method: 'POST',
    path: '/api/v1/tasks/creates-from-plan',
    core: 'createTasksFromPlan',
    args: 'payload',
    input: { runtimeId: 'string', workspaceId: 'string', proposals: 'array', enabled: 'boolean?' },
    capability: 'tasks.createsFromPlan',
    clients: ['web', 'desktop'],
    inputType:
      '{ runtimeId: string; workspaceId: string; proposals: PlanProposal[]; enabled?: boolean }',
  },
] as const satisfies readonly Operation[]
