/** workspaces operations. Wire identifiers and client scopes are stable. */
import type { Operation } from '../types.ts'

export const workspacesOperations = [
  {
    id: 'workspaces.restore',
    fn: 'restoreWorkspace',
    method: 'POST',
    path: '/api/v1/workspaces/restore',
    core: 'restoreWorkspaceById',
    args: ['workspaceId'],
    input: { workspaceId: 'string' },
    capability: 'workspaces.restore',
    clients: ['web', 'desktop'],
    inputType: '{ workspaceId: string }',
  },
  {
    id: 'workspaces.runBaseline',
    fn: 'runWorkspaceBaseline',
    method: 'POST',
    path: '/api/v1/workspaces/run-baseline',
    core: 'runWorkspaceBaseline',
    args: ['workspaceId'],
    input: { workspaceId: 'string' },
    capability: 'workspaces.runBaseline',
    clients: ['web', 'desktop'],
    inputType: '{ workspaceId: string }',
  },
  {
    id: 'workspaces.list',
    fn: 'listWorkspaces',
    method: 'GET',
    path: '/api/v1/workspaces/list',
    core: 'listWorkspaces',
    args: ['projectId'],
    input: { projectId: 'string?' },
    inputOptional: true,
    capability: 'workspaces.list',
    clients: ['web', 'desktop'],
    inputType: '{ projectId?: string }',
  },
  {
    id: 'workspaces.retrySetup',
    fn: 'retryWorkspaceSetup',
    method: 'POST',
    path: '/api/v1/workspaces/retry-setup',
    core: 'runSetup',
    args: ['id'],
    input: { id: 'string' },
    capability: 'workspaces.retrySetup',
    clients: ['web', 'desktop'],
    inputType: '{ id: string }',
  },
  {
    id: 'workspaces.archive',
    fn: 'archiveWorkspace',
    method: 'POST',
    path: '/api/v1/workspaces/archive',
    core: 'archiveWorkspace',
    args: ['id', 'force'],
    input: { id: 'string', force: 'boolean' },
    capability: 'workspaces.archive',
    clients: ['web', 'desktop'],
    inputType: '{ id: string; force: boolean }',
  },
] as const satisfies readonly Operation[]
