/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as RuntimesRouteImport } from './routes/runtimes'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as CloudCallbackRouteImport } from './routes/cloud.callback'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as IntegrationsProviderRouteImport } from './routes/integrations.$provider'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as RunsNewRouteImport } from './routes/runs.new'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as ApiActivityStreamRouteImport } from './routes/api/activity/stream'
import { Route as ApiMobileDashboardRouteImport } from './routes/api/mobile/dashboard'
import { Route as ApiMobileMeRouteImport } from './routes/api/mobile/me'
import { Route as ApiMobilePairRouteImport } from './routes/api/mobile/pair'
import { Route as ApiMobileUnpairRouteImport } from './routes/api/mobile/unpair'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiMcpOauthCallbackRouteImport } from './routes/api/mcp/oauth/callback'
import { Route as ApiMobileActivityStreamRouteImport } from './routes/api/mobile/activity.stream'
import { Route as ApiMobilePushRegisterRouteImport } from './routes/api/mobile/push.register'
import { Route as ApiMobileRunsIndexRouteImport } from './routes/api/mobile/runs/index'
import { Route as ApiMobileTasksIndexRouteImport } from './routes/api/mobile/tasks/index'
import { Route as ApiRunsRunIdAttachmentRouteImport } from './routes/api/runs/$runId/attachment'
import { Route as ApiRunsRunIdStreamRouteImport } from './routes/api/runs/$runId/stream'
import { Route as ApiRunsRunIdUiStreamRouteImport } from './routes/api/runs/$runId/ui-stream'
import { Route as ApiMobileRunsRunIdIndexRouteImport } from './routes/api/mobile/runs/$runId/index'
import { Route as ApiMobileRunsRunIdApprovalsRouteImport } from './routes/api/mobile/runs/$runId/approvals'
import { Route as ApiMobileRunsRunIdCancelRouteImport } from './routes/api/mobile/runs/$runId/cancel'
import { Route as ApiMobileRunsRunIdDiffRouteImport } from './routes/api/mobile/runs/$runId/diff'
import { Route as ApiMobileRunsRunIdFilesRouteImport } from './routes/api/mobile/runs/$runId/files'
import { Route as ApiMobileRunsRunIdMessageRouteImport } from './routes/api/mobile/runs/$runId/message'
import { Route as ApiMobileRunsRunIdStreamRouteImport } from './routes/api/mobile/runs/$runId/stream'
import { Route as ApiMobileTasksTaskIdRunRouteImport } from './routes/api/mobile/tasks/$taskId/run'
import { Route as ApiMobileTasksTaskIdToggleRouteImport } from './routes/api/mobile/tasks/$taskId/toggle'
import { Route as ApiMobileRunsRunIdDiffFileRouteImport } from './routes/api/mobile/runs/$runId/diff.file'
import { Route as ApiMobileRunsRunIdFilesContentRouteImport } from './routes/api/mobile/runs/$runId/files.content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimesRoute = RuntimesRouteImport.update({
  id: '/runtimes',
  path: '/runtimes',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudCallbackRoute = CloudCallbackRouteImport.update({
  id: '/cloud/callback',
  path: '/cloud/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const IntegrationsProviderRoute = IntegrationsProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => IntegrationsRoute,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityStreamRoute = ApiActivityStreamRouteImport.update({
  id: '/api/activity/stream',
  path: '/api/activity/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileDashboardRoute = ApiMobileDashboardRouteImport.update({
  id: '/api/mobile/dashboard',
  path: '/api/mobile/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileMeRoute = ApiMobileMeRouteImport.update({
  id: '/api/mobile/me',
  path: '/api/mobile/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePairRoute = ApiMobilePairRouteImport.update({
  id: '/api/mobile/pair',
  path: '/api/mobile/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileUnpairRoute = ApiMobileUnpairRouteImport.update({
  id: '/api/mobile/unpair',
  path: '/api/mobile/unpair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthCallbackRoute = ApiMcpOauthCallbackRouteImport.update({
  id: '/api/mcp/oauth/callback',
  path: '/api/mcp/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileActivityStreamRoute = ApiMobileActivityStreamRouteImport.update({
  id: '/api/mobile/activity/stream',
  path: '/api/mobile/activity/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePushRegisterRoute = ApiMobilePushRegisterRouteImport.update({
  id: '/api/mobile/push/register',
  path: '/api/mobile/push/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRunsIndexRoute = ApiMobileRunsIndexRouteImport.update({
  id: '/api/mobile/runs/',
  path: '/api/mobile/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileTasksIndexRoute = ApiMobileTasksIndexRouteImport.update({
  id: '/api/mobile/tasks/',
  path: '/api/mobile/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdAttachmentRoute = ApiRunsRunIdAttachmentRouteImport.update({
  id: '/api/runs/$runId/attachment',
  path: '/api/runs/$runId/attachment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdStreamRoute = ApiRunsRunIdStreamRouteImport.update({
  id: '/api/runs/$runId/stream',
  path: '/api/runs/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdUiStreamRoute = ApiRunsRunIdUiStreamRouteImport.update({
  id: '/api/runs/$runId/ui-stream',
  path: '/api/runs/$runId/ui-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRunsRunIdIndexRoute = ApiMobileRunsRunIdIndexRouteImport.update({
  id: '/api/mobile/runs/$runId/',
  path: '/api/mobile/runs/$runId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRunsRunIdApprovalsRoute =
  ApiMobileRunsRunIdApprovalsRouteImport.update({
    id: '/api/mobile/runs/$runId/approvals',
    path: '/api/mobile/runs/$runId/approvals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileRunsRunIdCancelRoute =
  ApiMobileRunsRunIdCancelRouteImport.update({
    id: '/api/mobile/runs/$runId/cancel',
    path: '/api/mobile/runs/$runId/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileRunsRunIdDiffRoute = ApiMobileRunsRunIdDiffRouteImport.update({
  id: '/api/mobile/runs/$runId/diff',
  path: '/api/mobile/runs/$runId/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRunsRunIdFilesRoute = ApiMobileRunsRunIdFilesRouteImport.update({
  id: '/api/mobile/runs/$runId/files',
  path: '/api/mobile/runs/$runId/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRunsRunIdMessageRoute =
  ApiMobileRunsRunIdMessageRouteImport.update({
    id: '/api/mobile/runs/$runId/message',
    path: '/api/mobile/runs/$runId/message',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileRunsRunIdStreamRoute =
  ApiMobileRunsRunIdStreamRouteImport.update({
    id: '/api/mobile/runs/$runId/stream',
    path: '/api/mobile/runs/$runId/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileTasksTaskIdRunRoute = ApiMobileTasksTaskIdRunRouteImport.update({
  id: '/api/mobile/tasks/$taskId/run',
  path: '/api/mobile/tasks/$taskId/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileTasksTaskIdToggleRoute =
  ApiMobileTasksTaskIdToggleRouteImport.update({
    id: '/api/mobile/tasks/$taskId/toggle',
    path: '/api/mobile/tasks/$taskId/toggle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileRunsRunIdDiffFileRoute =
  ApiMobileRunsRunIdDiffFileRouteImport.update({
    id: '/file',
    path: '/file',
    getParentRoute: () => ApiMobileRunsRunIdDiffRoute,
  } as any)
const ApiMobileRunsRunIdFilesContentRoute =
  ApiMobileRunsRunIdFilesContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => ApiMobileRunsRunIdFilesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/runtimes': typeof RuntimesRoute
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/cloud/callback': typeof CloudCallbackRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/new': typeof RunsNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/activity/stream': typeof ApiActivityStreamRoute
  '/api/mobile/dashboard': typeof ApiMobileDashboardRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/pair': typeof ApiMobilePairRoute
  '/api/mobile/unpair': typeof ApiMobileUnpairRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mobile/activity/stream': typeof ApiMobileActivityStreamRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/runs/$runId/attachment': typeof ApiRunsRunIdAttachmentRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/api/runs/$runId/ui-stream': typeof ApiRunsRunIdUiStreamRoute
  '/api/mobile/runs/': typeof ApiMobileRunsIndexRoute
  '/api/mobile/tasks/': typeof ApiMobileTasksIndexRoute
  '/api/mobile/runs/$runId/approvals': typeof ApiMobileRunsRunIdApprovalsRoute
  '/api/mobile/runs/$runId/cancel': typeof ApiMobileRunsRunIdCancelRoute
  '/api/mobile/runs/$runId/diff': typeof ApiMobileRunsRunIdDiffRouteWithChildren
  '/api/mobile/runs/$runId/files': typeof ApiMobileRunsRunIdFilesRouteWithChildren
  '/api/mobile/runs/$runId/message': typeof ApiMobileRunsRunIdMessageRoute
  '/api/mobile/runs/$runId/stream': typeof ApiMobileRunsRunIdStreamRoute
  '/api/mobile/tasks/$taskId/run': typeof ApiMobileTasksTaskIdRunRoute
  '/api/mobile/tasks/$taskId/toggle': typeof ApiMobileTasksTaskIdToggleRoute
  '/api/mobile/runs/$runId/': typeof ApiMobileRunsRunIdIndexRoute
  '/api/mobile/runs/$runId/diff/file': typeof ApiMobileRunsRunIdDiffFileRoute
  '/api/mobile/runs/$runId/files/content': typeof ApiMobileRunsRunIdFilesContentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/runtimes': typeof RuntimesRoute
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/cloud/callback': typeof CloudCallbackRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/new': typeof RunsNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/activity/stream': typeof ApiActivityStreamRoute
  '/api/mobile/dashboard': typeof ApiMobileDashboardRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/pair': typeof ApiMobilePairRoute
  '/api/mobile/unpair': typeof ApiMobileUnpairRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mobile/activity/stream': typeof ApiMobileActivityStreamRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/runs/$runId/attachment': typeof ApiRunsRunIdAttachmentRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/api/runs/$runId/ui-stream': typeof ApiRunsRunIdUiStreamRoute
  '/api/mobile/runs': typeof ApiMobileRunsIndexRoute
  '/api/mobile/tasks': typeof ApiMobileTasksIndexRoute
  '/api/mobile/runs/$runId/approvals': typeof ApiMobileRunsRunIdApprovalsRoute
  '/api/mobile/runs/$runId/cancel': typeof ApiMobileRunsRunIdCancelRoute
  '/api/mobile/runs/$runId/diff': typeof ApiMobileRunsRunIdDiffRouteWithChildren
  '/api/mobile/runs/$runId/files': typeof ApiMobileRunsRunIdFilesRouteWithChildren
  '/api/mobile/runs/$runId/message': typeof ApiMobileRunsRunIdMessageRoute
  '/api/mobile/runs/$runId/stream': typeof ApiMobileRunsRunIdStreamRoute
  '/api/mobile/tasks/$taskId/run': typeof ApiMobileTasksTaskIdRunRoute
  '/api/mobile/tasks/$taskId/toggle': typeof ApiMobileTasksTaskIdToggleRoute
  '/api/mobile/runs/$runId': typeof ApiMobileRunsRunIdIndexRoute
  '/api/mobile/runs/$runId/diff/file': typeof ApiMobileRunsRunIdDiffFileRoute
  '/api/mobile/runs/$runId/files/content': typeof ApiMobileRunsRunIdFilesContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/runtimes': typeof RuntimesRoute
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/cloud/callback': typeof CloudCallbackRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/new': typeof RunsNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/activity/stream': typeof ApiActivityStreamRoute
  '/api/mobile/dashboard': typeof ApiMobileDashboardRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/pair': typeof ApiMobilePairRoute
  '/api/mobile/unpair': typeof ApiMobileUnpairRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mobile/activity/stream': typeof ApiMobileActivityStreamRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/runs/$runId/attachment': typeof ApiRunsRunIdAttachmentRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/api/runs/$runId/ui-stream': typeof ApiRunsRunIdUiStreamRoute
  '/api/mobile/runs/': typeof ApiMobileRunsIndexRoute
  '/api/mobile/tasks/': typeof ApiMobileTasksIndexRoute
  '/api/mobile/runs/$runId/approvals': typeof ApiMobileRunsRunIdApprovalsRoute
  '/api/mobile/runs/$runId/cancel': typeof ApiMobileRunsRunIdCancelRoute
  '/api/mobile/runs/$runId/diff': typeof ApiMobileRunsRunIdDiffRouteWithChildren
  '/api/mobile/runs/$runId/files': typeof ApiMobileRunsRunIdFilesRouteWithChildren
  '/api/mobile/runs/$runId/message': typeof ApiMobileRunsRunIdMessageRoute
  '/api/mobile/runs/$runId/stream': typeof ApiMobileRunsRunIdStreamRoute
  '/api/mobile/tasks/$taskId/run': typeof ApiMobileTasksTaskIdRunRoute
  '/api/mobile/tasks/$taskId/toggle': typeof ApiMobileTasksTaskIdToggleRoute
  '/api/mobile/runs/$runId/': typeof ApiMobileRunsRunIdIndexRoute
  '/api/mobile/runs/$runId/diff/file': typeof ApiMobileRunsRunIdDiffFileRoute
  '/api/mobile/runs/$runId/files/content': typeof ApiMobileRunsRunIdFilesContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/integrations'
    | '/mcp'
    | '/notifications'
    | '/planner'
    | '/runtimes'
    | '/usage'
    | '/welcome'
    | '/cloud/callback'
    | '/integrations/$provider'
    | '/runs/$runId'
    | '/runs/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/integrations/'
    | '/runs/'
    | '/tasks/'
    | '/api/activity/stream'
    | '/api/mobile/dashboard'
    | '/api/mobile/me'
    | '/api/mobile/pair'
    | '/api/mobile/unpair'
    | '/api/v1/$'
    | '/api/mcp/oauth/callback'
    | '/api/mobile/activity/stream'
    | '/api/mobile/push/register'
    | '/api/runs/$runId/attachment'
    | '/api/runs/$runId/stream'
    | '/api/runs/$runId/ui-stream'
    | '/api/mobile/runs/'
    | '/api/mobile/tasks/'
    | '/api/mobile/runs/$runId/approvals'
    | '/api/mobile/runs/$runId/cancel'
    | '/api/mobile/runs/$runId/diff'
    | '/api/mobile/runs/$runId/files'
    | '/api/mobile/runs/$runId/message'
    | '/api/mobile/runs/$runId/stream'
    | '/api/mobile/tasks/$taskId/run'
    | '/api/mobile/tasks/$taskId/toggle'
    | '/api/mobile/runs/$runId/'
    | '/api/mobile/runs/$runId/diff/file'
    | '/api/mobile/runs/$runId/files/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/mcp'
    | '/notifications'
    | '/planner'
    | '/runtimes'
    | '/usage'
    | '/welcome'
    | '/cloud/callback'
    | '/integrations/$provider'
    | '/runs/$runId'
    | '/runs/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/integrations'
    | '/runs'
    | '/tasks'
    | '/api/activity/stream'
    | '/api/mobile/dashboard'
    | '/api/mobile/me'
    | '/api/mobile/pair'
    | '/api/mobile/unpair'
    | '/api/v1/$'
    | '/api/mcp/oauth/callback'
    | '/api/mobile/activity/stream'
    | '/api/mobile/push/register'
    | '/api/runs/$runId/attachment'
    | '/api/runs/$runId/stream'
    | '/api/runs/$runId/ui-stream'
    | '/api/mobile/runs'
    | '/api/mobile/tasks'
    | '/api/mobile/runs/$runId/approvals'
    | '/api/mobile/runs/$runId/cancel'
    | '/api/mobile/runs/$runId/diff'
    | '/api/mobile/runs/$runId/files'
    | '/api/mobile/runs/$runId/message'
    | '/api/mobile/runs/$runId/stream'
    | '/api/mobile/tasks/$taskId/run'
    | '/api/mobile/tasks/$taskId/toggle'
    | '/api/mobile/runs/$runId'
    | '/api/mobile/runs/$runId/diff/file'
    | '/api/mobile/runs/$runId/files/content'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/integrations'
    | '/mcp'
    | '/notifications'
    | '/planner'
    | '/runtimes'
    | '/usage'
    | '/welcome'
    | '/cloud/callback'
    | '/integrations/$provider'
    | '/runs/$runId'
    | '/runs/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/integrations/'
    | '/runs/'
    | '/tasks/'
    | '/api/activity/stream'
    | '/api/mobile/dashboard'
    | '/api/mobile/me'
    | '/api/mobile/pair'
    | '/api/mobile/unpair'
    | '/api/v1/$'
    | '/api/mcp/oauth/callback'
    | '/api/mobile/activity/stream'
    | '/api/mobile/push/register'
    | '/api/runs/$runId/attachment'
    | '/api/runs/$runId/stream'
    | '/api/runs/$runId/ui-stream'
    | '/api/mobile/runs/'
    | '/api/mobile/tasks/'
    | '/api/mobile/runs/$runId/approvals'
    | '/api/mobile/runs/$runId/cancel'
    | '/api/mobile/runs/$runId/diff'
    | '/api/mobile/runs/$runId/files'
    | '/api/mobile/runs/$runId/message'
    | '/api/mobile/runs/$runId/stream'
    | '/api/mobile/tasks/$taskId/run'
    | '/api/mobile/tasks/$taskId/toggle'
    | '/api/mobile/runs/$runId/'
    | '/api/mobile/runs/$runId/diff/file'
    | '/api/mobile/runs/$runId/files/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  McpRoute: typeof McpRoute
  NotificationsRoute: typeof NotificationsRoute
  PlannerRoute: typeof PlannerRoute
  RuntimesRoute: typeof RuntimesRoute
  UsageRoute: typeof UsageRoute
  WelcomeRoute: typeof WelcomeRoute
  CloudCallbackRoute: typeof CloudCallbackRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsNewRoute: typeof RunsNewRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksNewRoute: typeof TasksNewRoute
  RunsIndexRoute: typeof RunsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiActivityStreamRoute: typeof ApiActivityStreamRoute
  ApiMobileDashboardRoute: typeof ApiMobileDashboardRoute
  ApiMobileMeRoute: typeof ApiMobileMeRoute
  ApiMobilePairRoute: typeof ApiMobilePairRoute
  ApiMobileUnpairRoute: typeof ApiMobileUnpairRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiMcpOauthCallbackRoute: typeof ApiMcpOauthCallbackRoute
  ApiMobileActivityStreamRoute: typeof ApiMobileActivityStreamRoute
  ApiMobilePushRegisterRoute: typeof ApiMobilePushRegisterRoute
  ApiRunsRunIdAttachmentRoute: typeof ApiRunsRunIdAttachmentRoute
  ApiRunsRunIdStreamRoute: typeof ApiRunsRunIdStreamRoute
  ApiRunsRunIdUiStreamRoute: typeof ApiRunsRunIdUiStreamRoute
  ApiMobileRunsIndexRoute: typeof ApiMobileRunsIndexRoute
  ApiMobileTasksIndexRoute: typeof ApiMobileTasksIndexRoute
  ApiMobileRunsRunIdApprovalsRoute: typeof ApiMobileRunsRunIdApprovalsRoute
  ApiMobileRunsRunIdCancelRoute: typeof ApiMobileRunsRunIdCancelRoute
  ApiMobileRunsRunIdDiffRoute: typeof ApiMobileRunsRunIdDiffRouteWithChildren
  ApiMobileRunsRunIdFilesRoute: typeof ApiMobileRunsRunIdFilesRouteWithChildren
  ApiMobileRunsRunIdMessageRoute: typeof ApiMobileRunsRunIdMessageRoute
  ApiMobileRunsRunIdStreamRoute: typeof ApiMobileRunsRunIdStreamRoute
  ApiMobileTasksTaskIdRunRoute: typeof ApiMobileTasksTaskIdRunRoute
  ApiMobileTasksTaskIdToggleRoute: typeof ApiMobileTasksTaskIdToggleRoute
  ApiMobileRunsRunIdIndexRoute: typeof ApiMobileRunsRunIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtimes': {
      id: '/runtimes'
      path: '/runtimes'
      fullPath: '/runtimes'
      preLoaderRoute: typeof RuntimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/callback': {
      id: '/cloud/callback'
      path: '/cloud/callback'
      fullPath: '/cloud/callback'
      preLoaderRoute: typeof CloudCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/$provider': {
      id: '/integrations/$provider'
      path: '/$provider'
      fullPath: '/integrations/$provider'
      preLoaderRoute: typeof IntegrationsProviderRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity/stream': {
      id: '/api/activity/stream'
      path: '/api/activity/stream'
      fullPath: '/api/activity/stream'
      preLoaderRoute: typeof ApiActivityStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/dashboard': {
      id: '/api/mobile/dashboard'
      path: '/api/mobile/dashboard'
      fullPath: '/api/mobile/dashboard'
      preLoaderRoute: typeof ApiMobileDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/me': {
      id: '/api/mobile/me'
      path: '/api/mobile/me'
      fullPath: '/api/mobile/me'
      preLoaderRoute: typeof ApiMobileMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/pair': {
      id: '/api/mobile/pair'
      path: '/api/mobile/pair'
      fullPath: '/api/mobile/pair'
      preLoaderRoute: typeof ApiMobilePairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/unpair': {
      id: '/api/mobile/unpair'
      path: '/api/mobile/unpair'
      fullPath: '/api/mobile/unpair'
      preLoaderRoute: typeof ApiMobileUnpairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/oauth/callback': {
      id: '/api/mcp/oauth/callback'
      path: '/api/mcp/oauth/callback'
      fullPath: '/api/mcp/oauth/callback'
      preLoaderRoute: typeof ApiMcpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/activity/stream': {
      id: '/api/mobile/activity/stream'
      path: '/api/mobile/activity/stream'
      fullPath: '/api/mobile/activity/stream'
      preLoaderRoute: typeof ApiMobileActivityStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/push/register': {
      id: '/api/mobile/push/register'
      path: '/api/mobile/push/register'
      fullPath: '/api/mobile/push/register'
      preLoaderRoute: typeof ApiMobilePushRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/': {
      id: '/api/mobile/runs/'
      path: '/api/mobile/runs'
      fullPath: '/api/mobile/runs/'
      preLoaderRoute: typeof ApiMobileRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/tasks/': {
      id: '/api/mobile/tasks/'
      path: '/api/mobile/tasks'
      fullPath: '/api/mobile/tasks/'
      preLoaderRoute: typeof ApiMobileTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/attachment': {
      id: '/api/runs/$runId/attachment'
      path: '/api/runs/$runId/attachment'
      fullPath: '/api/runs/$runId/attachment'
      preLoaderRoute: typeof ApiRunsRunIdAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/stream': {
      id: '/api/runs/$runId/stream'
      path: '/api/runs/$runId/stream'
      fullPath: '/api/runs/$runId/stream'
      preLoaderRoute: typeof ApiRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/ui-stream': {
      id: '/api/runs/$runId/ui-stream'
      path: '/api/runs/$runId/ui-stream'
      fullPath: '/api/runs/$runId/ui-stream'
      preLoaderRoute: typeof ApiRunsRunIdUiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/$runId/': {
      id: '/api/mobile/runs/$runId/'
      path: '/api/mobile/runs/$runId'
      fullPath: '/api/mobile/runs/$runId/'
      preLoaderRoute: typeof ApiMobileRunsRunIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/$runId/approvals': {
      id: '/api/mobile/runs/$runId/approvals'
      path: '/api/mobile/runs/$runId/approvals'
      fullPath: '/api/mobile/runs/$runId/approvals'
      preLoaderRoute: typeof ApiMobileRunsRunIdApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/$runId/cancel': {
      id: '/api/mobile/runs/$runId/cancel'
      path: '/api/mobile/runs/$runId/cancel'
      fullPath: '/api/mobile/runs/$runId/cancel'
      preLoaderRoute: typeof ApiMobileRunsRunIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/$runId/diff': {
      id: '/api/mobile/runs/$runId/diff'
      path: '/api/mobile/runs/$runId/diff'
      fullPath: '/api/mobile/runs/$runId/diff'
      preLoaderRoute: typeof ApiMobileRunsRunIdDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/$runId/files': {
      id: '/api/mobile/runs/$runId/files'
      path: '/api/mobile/runs/$runId/files'
      fullPath: '/api/mobile/runs/$runId/files'
      preLoaderRoute: typeof ApiMobileRunsRunIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/$runId/message': {
      id: '/api/mobile/runs/$runId/message'
      path: '/api/mobile/runs/$runId/message'
      fullPath: '/api/mobile/runs/$runId/message'
      preLoaderRoute: typeof ApiMobileRunsRunIdMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/$runId/stream': {
      id: '/api/mobile/runs/$runId/stream'
      path: '/api/mobile/runs/$runId/stream'
      fullPath: '/api/mobile/runs/$runId/stream'
      preLoaderRoute: typeof ApiMobileRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/tasks/$taskId/run': {
      id: '/api/mobile/tasks/$taskId/run'
      path: '/api/mobile/tasks/$taskId/run'
      fullPath: '/api/mobile/tasks/$taskId/run'
      preLoaderRoute: typeof ApiMobileTasksTaskIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/tasks/$taskId/toggle': {
      id: '/api/mobile/tasks/$taskId/toggle'
      path: '/api/mobile/tasks/$taskId/toggle'
      fullPath: '/api/mobile/tasks/$taskId/toggle'
      preLoaderRoute: typeof ApiMobileTasksTaskIdToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/runs/$runId/diff/file': {
      id: '/api/mobile/runs/$runId/diff/file'
      path: '/file'
      fullPath: '/api/mobile/runs/$runId/diff/file'
      preLoaderRoute: typeof ApiMobileRunsRunIdDiffFileRouteImport
      parentRoute: typeof ApiMobileRunsRunIdDiffRoute
    }
    '/api/mobile/runs/$runId/files/content': {
      id: '/api/mobile/runs/$runId/files/content'
      path: '/content'
      fullPath: '/api/mobile/runs/$runId/files/content'
      preLoaderRoute: typeof ApiMobileRunsRunIdFilesContentRouteImport
      parentRoute: typeof ApiMobileRunsRunIdFilesRoute
    }
  }
}

interface IntegrationsRouteChildren {
  IntegrationsProviderRoute: typeof IntegrationsProviderRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsProviderRoute: IntegrationsProviderRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface ApiMobileRunsRunIdDiffRouteChildren {
  ApiMobileRunsRunIdDiffFileRoute: typeof ApiMobileRunsRunIdDiffFileRoute
}

const ApiMobileRunsRunIdDiffRouteChildren: ApiMobileRunsRunIdDiffRouteChildren =
  {
    ApiMobileRunsRunIdDiffFileRoute: ApiMobileRunsRunIdDiffFileRoute,
  }

const ApiMobileRunsRunIdDiffRouteWithChildren =
  ApiMobileRunsRunIdDiffRoute._addFileChildren(
    ApiMobileRunsRunIdDiffRouteChildren,
  )

interface ApiMobileRunsRunIdFilesRouteChildren {
  ApiMobileRunsRunIdFilesContentRoute: typeof ApiMobileRunsRunIdFilesContentRoute
}

const ApiMobileRunsRunIdFilesRouteChildren: ApiMobileRunsRunIdFilesRouteChildren =
  {
    ApiMobileRunsRunIdFilesContentRoute: ApiMobileRunsRunIdFilesContentRoute,
  }

const ApiMobileRunsRunIdFilesRouteWithChildren =
  ApiMobileRunsRunIdFilesRoute._addFileChildren(
    ApiMobileRunsRunIdFilesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  McpRoute: McpRoute,
  NotificationsRoute: NotificationsRoute,
  PlannerRoute: PlannerRoute,
  RuntimesRoute: RuntimesRoute,
  UsageRoute: UsageRoute,
  WelcomeRoute: WelcomeRoute,
  CloudCallbackRoute: CloudCallbackRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  RunsNewRoute: RunsNewRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  RunsIndexRoute: RunsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiActivityStreamRoute: ApiActivityStreamRoute,
  ApiMobileDashboardRoute: ApiMobileDashboardRoute,
  ApiMobileMeRoute: ApiMobileMeRoute,
  ApiMobilePairRoute: ApiMobilePairRoute,
  ApiMobileUnpairRoute: ApiMobileUnpairRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiMcpOauthCallbackRoute: ApiMcpOauthCallbackRoute,
  ApiMobileActivityStreamRoute: ApiMobileActivityStreamRoute,
  ApiMobilePushRegisterRoute: ApiMobilePushRegisterRoute,
  ApiRunsRunIdAttachmentRoute: ApiRunsRunIdAttachmentRoute,
  ApiRunsRunIdStreamRoute: ApiRunsRunIdStreamRoute,
  ApiRunsRunIdUiStreamRoute: ApiRunsRunIdUiStreamRoute,
  ApiMobileRunsIndexRoute: ApiMobileRunsIndexRoute,
  ApiMobileTasksIndexRoute: ApiMobileTasksIndexRoute,
  ApiMobileRunsRunIdApprovalsRoute: ApiMobileRunsRunIdApprovalsRoute,
  ApiMobileRunsRunIdCancelRoute: ApiMobileRunsRunIdCancelRoute,
  ApiMobileRunsRunIdDiffRoute: ApiMobileRunsRunIdDiffRouteWithChildren,
  ApiMobileRunsRunIdFilesRoute: ApiMobileRunsRunIdFilesRouteWithChildren,
  ApiMobileRunsRunIdMessageRoute: ApiMobileRunsRunIdMessageRoute,
  ApiMobileRunsRunIdStreamRoute: ApiMobileRunsRunIdStreamRoute,
  ApiMobileTasksTaskIdRunRoute: ApiMobileTasksTaskIdRunRoute,
  ApiMobileTasksTaskIdToggleRoute: ApiMobileTasksTaskIdToggleRoute,
  ApiMobileRunsRunIdIndexRoute: ApiMobileRunsRunIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
